### ISSUE TITLE
Remove description defaulting to the trigger?

### ISSUE THREAD

**Issue by bew** [L3MON4D3/LuaSnip#1006]
While working on #1005 I noticed the snippet description defaults to the snippet trigger, why?

I'm thinking it would be more flexible to not have a default for the description, and scripts that want to use this _could_ decide to use the trigger as default or not.

For example `cmp_luasnip` already shows the trigger at the top:
![Screenshot_20230917_181405](https://github.com/L3MON4D3/LuaSnip/assets/9730330/c5d1be45-4dd0-4170-a3c6-b3a1777ce553)
without a description the doc looks like:
![Screenshot_20230917_181700](https://github.com/L3MON4D3/LuaSnip/assets/9730330/4ddc98f0-a328-4a62-855a-00772ae21460)
Which repeats the trigger for no reason
Without the default to trigger that would look like:
![Screenshot_20230917_181532](https://github.com/L3MON4D3/LuaSnip/assets/9730330/f737e218-d10e-4927-88d3-574cc101760d)
Which is cleaner IMO.

**Comment by L3MON4D3** [comment]
Hmmm good point.
I think my thought process was to just put anything in there, so that consumers habe a simple interface (description is always a string[]). Until now I hadn't considered that we obviously lose the "no-description"-option.

One pragmatic, and backwards compatible way of solving this would be to have consumers check if the description is the same as the trigger. When phrased as "prevent putting the same information twice" it doesn't even seem that bad :D

**Comment by bew** [comment]
note: Actually the first text in doc window is the snip name:
https://github.com/saadparwaiz1/cmp_luasnip/blob/18095520391186d634a/lua/cmp_luasnip/init.lua#L36
Which is usually the trigger (unless specified differently while defining the snippet)

**Comment by L3MON4D3** [comment]
Ahhhh alright :+1:
I'll close this, I think consumers can take care of this
