### ISSUE TITLE
Help wanted: How to disable function argument snippets?

### ISSUE THREAD

**Issue by bravoecho** [L3MON4D3/LuaSnip#1015]
Hi, I am trying to disable snippets for function calls, as I already have signature help. I have searched documentation sources and online discussions, but I can not find a setting that would allow this.

This is the issue, for example:

<img width="409" alt="image" src="https://github.com/L3MON4D3/LuaSnip/assets/698828/e9d4c0ee-8905-446b-a2b2-10f8d7e1b9d9">

I would rather be able to type the arguments without having to use the "jump to next element" shortcut that I have configured for LuaSnip.

Thanks! 🙂

**Comment by L3MON4D3** [comment]
Ouh, I think the proper way would be to disable that on a per-languageserver-basis, 
but since most languageservers don't have those fine-grained options, that's not really possible.

Another option to still remove the snippets would be to manually filter the results returned by the languageserver. [Here's](https://github.com/L3MON4D3/Dotfiles/blob/8f1b685c5945e07e28acc7d0d1df7baff8c64e0f/.config/nvim/lua/plugins/lspconfig.lua#L90-L147) a utility-function for doing that.
The underlying idea is to hook between the languageserver and eg. `nvim-cmp`, and just filter the completion-items returned by the server.
In the linked code-section, for example, returned snippets are modified, and unhelpful inlay-hints are discarded.

I guess you'd have to more-or-less put the code for discarding inlay-hints in the function responsible for modifying completion-items, and then would only need some way to recognize which completion-items are snippets (easy, check `item.insertTextFormat`) and function-calls (maybe a simple `string.match` on the `item.textEdit.newText` is enough?), and then discard those.

**Comment by bravoecho** [comment]
Ah, thank you for the pointers, @L3MON4D3, I'll have a stab at that 🙂

**Comment by bravoecho** [comment]
Just a quick update, it might be useful if anyone ever bumps into this thread.

The behaviour wasn't caused by LuaSnip, but by an option of the LSP client, that I had set without considering the implications and then forgotten about. 

```lua
lspconfig.gopls.setup({
  -- ...
  settings = {
    gopls = {
      -- ...
      usePlaceholders = true, -- <-- NOTE: this caused the issue
    },
  },
})
```

This would hook into LuaSnip, so that one could navigate the placeholders with the keymaps configured for LuaSnip.

Setting the `usePlaceholders` option to `false` solved the issue: 

<img width="395" alt="image" src="https://github.com/L3MON4D3/LuaSnip/assets/698828/35fccace-f0d6-4835-95ac-95e20bad2385">

Apologies for the confusion!
