### ISSUE TITLE
Cursor does not jump to end of autosnippet when using nested autosnippets

### ISSUE THREAD

**Issue by zerogtiger** [L3MON4D3/LuaSnip#1070]
(See config files below) When I type `mmff` in a LaTeX file, it will result in the expansion of `$$`, placing my cursor between the "$"s and subsequently, `\frac{}{}`, placing my cursor between the first set of curly braces. The final result of this typing is `$\frac{*}{}$`, where "`*`" indicates where my cursor rests. 

The expected behaviour is that when I press `<C-l>` 4 times, I will eventually land after the two "`$`" signs, like so `$\frac{}{}$*`, where `*` indicates where my cursor SHOULD be. However, regardless of the number of times I press `<C-l>` to try to jump forward, my cursor is stuck between the closing "}" of the fraction and the closing "$", like so `$\frac{}{}*$`. 

This issue does not occur if I place something before I type "`ff`". For instance, if I type `mm ff`, resulting in `$ \frac{*}{}$`, I am able to jump to after the dollar signs. 

Is this a bug? If so, could a patch be provided as it is quite annoying and inconsistent with the expected bahaviour. 

I am using Vimtex, so certain config files below calls certain vimtex functions. 

Related config files: 

```lua
-- "~/.config/nvim/luasnip/tex/math.lua"

-- Math context detection
local tex = {}
tex.in_mathzone = function() return vim.fn['vimtex#syntax#in_mathzone']() == 1 end
tex.in_text = function() return not tex.in_mathzone() end

local line_begin = require("luasnip.extras.expand_conditions").line_begin

-- Return snippet tables
return
  {
    -- INLINE MATH
    s({trig = "([^%l])mm", regTrig = true, wordTrig = false, snippetType="autosnippet"},
      fmta(
        "<>$<>$",
        {
          f( function(_, snip) return snip.captures[1] end ),
          d(1, get_visual),
        }
      )
    ),
  -- FRACTION,
  s({trig = "([^%a])ff", wordTrig = false, regTrig = true, snippetType="autosnippet"},
    fmta(
      "<>\\frac{<>}{<>}",
      {
        f( function(_, snip) return snip.captures[1] end ),
        d(1, get_visual),
        i(2),
      }
    ),
    {condition = tex.in_mathzone}
  ),
}
```

```lua
-- "~/.config/nvim/after/plugin/luasnip.lua"

local ls = require("luasnip")
local s = ls.snippet
local sn = ls.snippet_node
local t = ls.text_node
local i = ls.insert_node
local f = ls.function_node
local d = ls.dynamic_node
local fmt = require("luasnip.extras.fmt").fmt
local fmta = require("luasnip.extras.fmt").fmta
local rep = require("luasnip.extras").rep

ls.config.set_config({ -- Setting LuaSnip config
    -- Enable autotriggered snippets
    enable_autosnippets = true,

    -- Use Tab (or some other key if you prefer) to trigger visual selection
    store_selection_keys = "<C-L>",

    update_events = 'TextChanged,TextChangedI'
})

vim.keymap.set({ "i" }, "<C-O>", function() ls.expand() end, { silent = true })
vim.keymap.set({ "i", "s" }, "<C-L>", function() ls.jump(1) end, { silent = true })
vim.keymap.set({ "i", "s" }, "<C-H>", function() ls.jump(-1) end, { silent = true })

vim.keymap.set({ "i", "s" }, "<C-E>", function()
    if ls.choice_active() then
        ls.change_choice(1)
    end
end, { silent = true })

-- Load snippets from ~/.config/nvim/LuaSnip/
require("luasnip.loaders.from_lua").load({ paths = "~/.config/nvim/luasnip/" })
```

**Comment by L3MON4D3** [comment]
Ahhh okay, the issue is that the `ff`-snippet deletes part of the `mm`-snippet.
If a part of a snippet that is not supposed to be deleted manually (eg. content of a textNode) is deleted from the buffer, the whole snippet is treated as invalid and as "don't jump in here", which is implemented to prevent jumping into deleted snippets (so, snippets whose text in the buffer was deleted with eg. `dd`).

In your case, the first `$` is part of the trigger of the `ff`-snippet, and thus deleted during the expansion of the snippet, which we detect subsequently, and then delete the `mm`-snippet, since part of it was deleted (and then you can't jump back into that later)

How to prevent this:
I'd say that the best way is to rewrite your snippet to use `condition` to implement this "no %a before proper trigger".
I'd even argue this is more idiomatic since you have this nice separation between the trigger, and what conditions the position of the trigger should fulfill (also, you can get rid of the functionNode which just re-inserts the deleted text)

In case you're not familiar with writing your own conditions, [here's](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#conditions) some general info on them. Also check out condition-objects (described immediately after) since there's a nice usecase for them here :D

**Comment by zerogtiger** [comment]
Hey, finally got time to address this problem. I have read through the help docs you've linked, though couldn't find any information on how to implement the "no %a before proper trigger" in luasnip with conditions. Could you give an example or some pointers to the implementation?
