### ISSUE TITLE
How to change the default "====" line in suggestions?

### ISSUE THREAD

**Issue by riazufila** [L3MON4D3/LuaSnip#146]
How do I change the default "=======" in [this](https://imgur.com/a/u9OLxt6)? Possibly to a straight line instead?

**Comment by leiserfg** [comment]
Luasnip does not draw that, should be in the completion plugging you are using.

**Comment by saadparwaiz1** [comment]
if you are using `nvim-cmp` with `cmp_luasnip` it's actually done [here](https://github.com/saadparwaiz1/cmp_luasnip/blob/da37737ab9c569013827d60915f8d598c1483bbc/lua/cmp_luasnip/init.lua#L12). I kept it as "=" because that's what nvim-compe used. but I can change it to "-" if you guys wantÂ


Here's the difference between the two:

![Screenshot 2021-09-02 at 14 22 40](https://user-images.githubusercontent.com/73385353/131851424-1ac27d2f-0b9f-4c2e-be49-5dc06a7e9c13.jpg)
![Screenshot 2021-09-02 at 14 24 18](https://user-images.githubusercontent.com/73385353/131851564-fd89016e-fd25-4c4e-95bc-85a3166891f8.jpg)

**Comment by riazufila** [comment]
> if you are using `nvim-cmp` with `cmp_luasnip` it's actually done [here](https://github.com/saadparwaiz1/cmp_luasnip/blob/da37737ab9c569013827d60915f8d598c1483bbc/lua/cmp_luasnip/init.lua#L12). I kept it as "=" because that's what nvim-compe used. but I can change it to "-" if you guys want
> 
> Here's the difference between the two:
> 
> ![Screenshot 2021-09-02 at 14 22 40](https://user-images.githubusercontent.com/73385353/131851424-1ac27d2f-0b9f-4c2e-be49-5dc06a7e9c13.jpg)
> ![Screenshot 2021-09-02 at 14 24 18](https://user-images.githubusercontent.com/73385353/131851564-fd89016e-fd25-4c4e-95bc-85a3166891f8.jpg)

Yeah Im using both of that plugin together. I think it looks nicer in the first picture. The other suggestions I got from completion have it like the first picture. I think itll be more uniform with nvim-cmp which should be the successor for nvim-compe :D

**Comment by bew** [comment]
The first one is definitely better, could you also reduce the spacings? (remove blank line between the --- line and the `require module` text, as well as keep only 1 blank line between the doc and the snippet template?

**Comment by saadparwaiz1** [comment]
> The first one is definitely better!
> 
> Could you also reduce the spacings?
> 
>     * remove blank line between the --- line and the `require module` text
> 
>     * keep only 1 blank line between the doc and the snippet template

@L3MON4D3 @leiserfg are you guys fine with these? I can update the completion source once you guys approve :)

**Comment by gegoune** [comment]
Just checked, looks way prettier now!

**Comment by saadparwaiz1** [comment]
Have merged the changes now. This issue can be closed
