### ISSUE TITLE
LSP snippets parsing error

### ISSUE THREAD

**Issue by DanielCardonaRojas** [L3MON4D3/LuaSnip#159]
VSCode seems to be able to parse snippets like this: (where you insert literally a $) 

```json
  "freezed class json serializable": {
        "prefix": "fzcj",
        "body": [
            "@freezed",
            "abstract class $1 with _$$1 {\n",
            "\tconst factory $1({}) = _$1;\n",
            "\tfactory $1.fromJson(Map<String, dynamic> json) => _$$1FromJson(json);\n",
            "}"
        ]
    },
```
I took me a while to discover that `$` needs to be escaped with `\\` if you want the literal character within the snippet.

Maybe documentation is enough.

**Comment by L3MON4D3** [comment]
Oh, it's possible that this case is similar to #141, where escaping is only necessary when ambiguous (ie. `\$1`). 
Will take a while, but I'll look into fixing that.

**Comment by leiserfg** [comment]
I guess  is that $$ is how vscode scapes $. Have a look at jquery snippets, that's how they do it there. Is kinda gross because they don't mention it in the specification.  
https://github.com/kspearrin/Visual-Studio-jQuery-Code-Snippets/blob/master/jQueryCodeSnippets/JavaScript/jQuery/jqAttrSet.snippet#L38

**Comment by L3MON4D3** [comment]
3a1b5d1 should do it :)
