### ISSUE TITLE
Transition from ultisnips

### ISSUE THREAD

**Issue by danjenson** [L3MON4D3/LuaSnip#201]
I have several custom ultisnips snippet files, `markdown.snippets` and `tex.snippets`. What is the easiest way to transition these over? Ultisnips had a directory where you could put these files and it would source them when appropriate; is there anything equivalent here? Also, is there an example of translating a snippet? Here is an example of how I wrote them before:

in `tex.snippet`
```
snippet math "Aligned Math Block"
\[
\begin{aligned}
	$1 &= $2 \\\\
\end{aligned}
\]
endsnippet
```

**Comment by leiserfg** [comment]
Unless you are using back ticks you can use the LSP format most of the time.

**Comment by L3MON4D3** [comment]
Yes, I'd recommend using something like sed or perl to translate a ultisnips-file to the json-format.
I experimented around a bit, using
```bash
perl -077 -pe 's/snippet ([^ ]+) "([^"]+)"\n(.*)\nendsnippet/"$2": {\n  "prefix": "$1",\n  "body": [\n$3\n  ]\n}/gs' test
```
with `test` containing your snippet, I get
```json
"Aligned Math Block": {
  "prefix": "math",
  "body": [
\]
\begin{aligned}
        $1 &= $2 \\\\
\end{aligned}
\]
  ]
}
```
What's obviously missing are the quotation marks aroung the lines, no idea if that's easily doable using perl one-liners, maybe you'll need something more powerful.
Pinging @timoleistner, because they were also interested in this
