### ISSUE TITLE
Ability to share input nodes (bidirectional edits) even between choices

### ISSUE THREAD

**Issue by stasjok** [L3MON4D3/LuaSnip#227]
I recently tried writing snippets in lua and found something I was missing. I think it's hard to implement, but maybe it's not.

It's not a big deal, really, but I'll try to show with a simple example:

```lua
ls.snippets = {
  all = {
    s("quotes", {
      c(1, {
        sn(nil, { t("'"), i(1, "shared"), t("'") }),
        sn(nil, { t('"'), i(1, "shared"), t('"') }),
      }),
    }),
    s("flatten", {
      t("flatten("),
      c(1, {
        i(nil, "shared"),
        sn(nil, { t("levels="), i(1, "shared") }),
      }),
      t(")"),
    }),
  },
}
```

First snippet (not a very practical example) is a choice between two snippets with different quotes. So if I started to edit text inside, it would be cool to be able to just switch to another choice (with different quotes) and continue to edit there. Then I can switch another time. The point is to preserve edited text between all choices.

Second snippet is basically some function in a language where you can pass either positional or named arguments. So a user can start to edit input nodes, than he can change the look of the snippet any time and continue to edit shared nodes.

It can be some complicated choices with multiple inputs, but some of those inputs are the same between choices (but not all of them).

In simple snippets I can use `rep` from extras. But it's not the same. Basically, I want an ability not only to clone an input node, but to edit it at any position. And the ability to reference nodes from other snippet nodes/choices.

**Comment by L3MON4D3** [comment]
Thats a great idea!
We could implement it using three new nodes, `choiceStore`, `choiceRestore` and `choiceRestoreDynamic` where
 - `choiceStore(pos, nodes, storeIndex)` extends `snippetNode` (so that more than just an `insertNode` could potentially be stored) and stores the text that is inside it when changing the choice at some `storeIndex`.
 - `choiceRestore(storeIndex)` is a `textNode`, with the difference that it gets it preselected text from the text at the `storeIndex`.
 - `choiceRestoreDynamic(pos, storeIndex)` is basically an `insertNode`, with the difference that it gets it preselected text from the text at the `storeIndex`
 
We could also make the text at the store-indices available to `functionNode` and `dynamicNode`, that way the mechanism would be even more powerful.
One problem with that would be that the `choiceNode`s aren't easily accessible (we pass snippets to those functions, so `choiceNode`s would have to be accessed from the snippets node-table :/ (maybe store the `choiceNode` a snippet is in inside all nodes, similar to `parent`?))

**Comment by L3MON4D3** [comment]
I thought about it some more, we could also introduce some kind of `storeNamespace(pos, nodes)`, (`snippetNode` with the ability to store the destroyed childrens text) instead. That would make writing `dynamicNodes` that remember text that was inserted over updates (right now the text from some `insertNode` has to be manually extracted to be available to the newly created `snippetNode`. As an example for that check out the javadoc-snippet in the README and its [source code](https://github.com/L3MON4D3/LuaSnip/blob/master/Examples/snippets.lua#L60-L141), `old_state` is used to store the nodes and get their text, which is pretty cumbersome. Using the `storeNamespace`, they could be set up to "automatically" store and restore their `insertNode`s text) much easier.

**Comment by L3MON4D3** [comment]
Obviously the store-nodes would have to have some simple aliases when we first implement them (for example, storing and restoring a single `insertNode` would look like this `choiceStore(1, {choiceRestoreDynamic(1, "somekey")}, "somekey")`) which is pretty unwieldly.
But aliased to eg. `insertLink(1, "somekey")`, all is well again :D

**Comment by stasjok** [comment]
So if I get you right, everything inside `choiceStore` is automatically saved under "somekey". `choiceRestore` and `choiceRestoreDynamic` get their text from this "somekey". So we need to combine `choiceStore` with `choiceRestoreDynamic` in order to save edited content. Is it stored/restored only when making a choice or dynamically after `updateevents`? In case of updateevents I see a potential problem with e.g. `choiceStore(1, {textNode("text"), choiceRestoreDynamic(1, "somekey")}, "somekey")`. Also a combination of choiceStore and "somekey" should be unique for snippet. And also we need to somehow provide a default value.

I thought about some general solution. I have an idea from user's point of view. I don't know if it can be implemented, maybe current state of thing doesn't allow it.

User can explicitly add `store` key in snippet. It's a table with stored defaults. Values can be string, table of strings (for multiline text) or function to allow default value be calculated from e.g. filename (function is evaluated one time when content of the store first accessed, then it replaced in store with evaluated content). And user can reference keys from this table in special nodes. For example:

```lua
ls.snippets = {
  all = {
    s({
      trig = "quotes",
      store = { somekey = "shared" }, -- <- string, table of strings or function?
    }, {
      c(1, {
        sn(nil, { t("'"), insertStored(1, "somekey"), t("'") }),
        sn(nil, { t('"'), insertStored(1, "somekey"), t('"') }),
      }),
    }),
    s({
      trig = "flatten",
      store = { levels = "1" },
    }, {
      t("flatten("),
      c(1, {
        insertStored(nil, "levels"),
        sn(nil, { t("levels="), insertStored(1, "levels") }),
      }),
      t(")"),
    }),
  },
}
```

So we have `insertStored(pos, key)` (or some other name) node, that get it's default text from stored value, and the content is automatically saved back to store whenever user changes it. We also have `textStored(key)` node, that just shows stored text (of course it should be updated after `updateevents`). There can be multiple insertNodes referencing same key. Their displayed text is also updated after `updateevents`. If "somekey" is not defined, than it's created automatically with empty string.

This way inside choiceNode or snippetNode we can use nodes with text from central store. Also a function from functionNode and dynamicNode have `snip` argument. So they can access store table from there. Also dynamicNode can return this `insertStored`s with some meaningful keys. And after snippet is reconstructed, we already have content stored under those "meaningful keys". But it should be a way for function in dynamicNode to set default values for this "meaningful keys". Maybe directly edit them via `snip.store`?

**Comment by L3MON4D3** [comment]
> So if I get you right, everything inside `choiceStore` is automatically saved under "somekey".

From the users POV automatically, actually we would store in `choiceStore:exit()` (see [changeChoice](https://github.com/L3MON4D3/LuaSnip/blob/a1580b62beaffad0d631219d1b14764b17ab63aa/lua/luasnip/nodes/choiceNode.lua#L168-L194) for a short snippet-lifecycle).

> `choiceRestore` and `choiceRestoreDynamic` get their text from this "somekey". So we need to combine `choiceStore` with `choiceRestoreDynamic` in order to save edited content.

Yes, exactly.

> Is it stored/restored only when making a choice or dynamically after `updateevents`?

On exit, IMO the store-restore function should only be for storing text that would otherwise be unaccessible.

> Also a combination of choiceStore and "somekey" should be unique for snippet.

Probably not, in 
```lua
      c(1, {
        sn(nil, { t("'"), insertStored(1, "somekey"), t("'") }),
        sn(nil, { t('"'), insertStored(1, "somekey"), t('"') }),
      })
```
we would have to store to the same key from both `insertStored`s, otherwise there would be nothing to restore for one of the two nodes.

> And also we need to somehow provide a default value.

Oh, good idea. So far I was only thinking of just returning a `""` for an as of then unused key, but letting the user provide default values as functions or strings would be pretty nice.

> I thought about some general solution. I have an idea from user's point of view. I don't know if it can be implemented, maybe current state of thing doesn't allow it.
> 
> User can explicitly add `store` key in snippet. It's a table with stored defaults. Values can be string, table of strings (for multiline text) or function to allow default value be calculated from e.g. filename (function is evaluated one time when content of the store first accessed, then it replaced in store with evaluated content). And user can reference keys from this table in special nodes. For example:
> 
> ```lua
> ls.snippets = {
>   all = {
>     s({
>       trig = "quotes",
>       store = { somekey = "shared" }, -- <- string, table of strings or function?
>     }, {
>       c(1, {
>         sn(nil, { t("'"), insertStored(1, "somekey"), t("'") }),
>         sn(nil, { t('"'), insertStored(1, "somekey"), t('"') }),
>       }),
>     }),
>     s({
>       trig = "flatten",
>       store = { levels = "1" },
>     }, {
>       t("flatten("),
>       c(1, {
>         insertStored(nil, "levels"),
>         sn(nil, { t("levels="), insertStored(1, "levels") }),
>       }),
>       t(")"),
>     }),
>   },
> }
> ```
> 
> So we have `insertStored(pos, key)` (or some other name) node, that get it's default text from stored value, and the content is automatically saved back to store whenever user changes it. We also have `textStored(key)` node, that just shows stored text (of course it should be updated after `updateevents`). There can be multiple insertNodes referencing same key. Their displayed text is also updated after `updateevents`. If "somekey" is not defined, than it's created automatically with empty string.

That's pretty much in line with what I was thinking, I wouldn't put the store-functionality into `snippet` or `snippetNode`, but in a separate type that inherits from `snippetNode`. Doing that you could still construct all snippets by doing something like
```lua
function storeSnippet(context, nodes)
    return return s(context, {storeNamespace(1, nodes)})
end
```
and then using `storeSnippet` (obviously you could also use a single-char name for less typing) instead of `s`.
 > 
> This way inside choiceNode or snippetNode we can use nodes with text from central store. Also a function from functionNode and dynamicNode have `snip` argument. So they can access store table from there.

Yes! The important thing is that `dynamic/functionNodes` pass their immediate parent to their function ([here](https://github.com/L3MON4D3/LuaSnip/blob/5b2c1dba655818d6d9724aaa945e397ae3d21b63/lua/luasnip/nodes/dynamicNode.lua#L103-L108))
> Also dynamicNode can return this `insertStored`s with some meaningful keys. And after snippet is reconstructed, we already have content stored under those "meaningful keys". But there should be a way for function in dynamicNode to set default values for this "meaningful keys". Maybe directly edit them via `snip.store`?

Yup, that should work pretty nicely, although it may be a bit hard to make useful, as the `choiceRestore`s won't be updated right away, only when they are reinserted.

**Comment by L3MON4D3** [comment]
I just realized we could also have the `choiceStore` store it's `nodes` not as text, but as `node`-objects. That would be useful if one would like to store the currently selected choice in a nested `choiceNode`.
I'm not entirely sure it that is implementable, I'll have to think about it.

**Comment by L3MON4D3** [comment]
Also, you're probably right with having the store-functionality inside `snippet`, `storeNamespace` only really need a table to store the key-nodes pairs and some functionality to default-initialize them, which isn't too much too add to the default `snippet`.

**Comment by L3MON4D3** [comment]
Check out #228, I implemented a first version there.
I kept pretty close to your ideas actually, turns out they integrated very naturally with the current design of everything :+1:

**Comment by stasjok** [comment]
One thing I wanted to ask. It's not a request to change anything, right now it is working as choices always were and should be. My original idea was to create snippets, where I can change a look of a snippet without changing current node. I mean changing surroundings any time I want and _continue typing_ (e.g. add optional arguments, change a design of comments or something else). So the snippet is pretty much the same, but surroundings are different. And with current implementation I have a small inconvenience with _continue typing_ part, because changing choice 1) selects a placeholder 2) move me to the first placeholder. Of course choices can be anything, so I can't ask it to save my position. But maybe I'm missing something? If nothing comes up in five minutes, than don't worry about that. I just need to design my snippets differently and not wrapping up entire snippet as choice.

**Comment by L3MON4D3** [comment]
Well, if you're inside a restoreNode while changing choice and that restoreNode also exists in the new choice, the cursor-position could be restored because we know that the text you were typing still exists.
Definitely a cool feature, could you open a new issue for that? I'd like to keep it separate from this because I'm not completely sure on how to implement it yet and it might take some time

**Comment by stasjok** [comment]
OK, closing this now, as #228 is merged.
