### ISSUE TITLE
No active choiceNode

### ISSUE THREAD

**Issue by cathaysia** [L3MON4D3/LuaSnip#237]
I'm using cmp with luasnip. And I had seen https://github.com/hrsh7th/nvim-cmp/issues/21, https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings#luasnip. However, luasnip can't jump to next placeholder. So I try:

```lua
vim.api.nvim_set_keymap('i', '<C-E>', ':lua require("luasnip").jump()', {})
```

Then I open a .c file, trigger a snip, and press C-E, then it faild.
![图片](https://user-images.githubusercontent.com/42114817/145221921-c38a94c4-d3c6-4001-9b39-6cc2a69286ef.png)

So I want know how to fix this? And no way jump to next placeholder?

**Comment by cathaysia** [comment]
Sorry, I find the answer:
```lua
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
```

**Comment by L3MON4D3** [comment]
Weird, that doesn't really have do anything with luasnip AFAICT.
Anyway, is it alright if this is closed?

**Comment by cathaysia** [comment]
Yes, sorry for my misktake

**Comment by krzykli** [comment]
Hm... running into the exact same problem and the capabilities workaround doesn't make a difference for me.
With luasnip active on an empty buffer pressing Enter in insert mode results in the same error message. Has anyone else hit the same thing? I'd really love to get my snippets working but because of that I need to keep the plugin disabled 😢 

My dotfiles: https://github.com/krzykli/dotfiles/tree/master/nvim
Using NVIM 0.6.0 with all plugins updated today.

**Comment by L3MON4D3** [comment]
What did you bind enter to? It's should be something like `jump` or `expand_or_jump`, not `change_choice`.
You can find example-mappings in the readme

**Comment by krzykli** [comment]
Yeah I might have jumped the gun here cause I can't repro it at the moment 🤦  The only mapping for enter is in my cmp
`        ['<CR>'] = cmp.mapping.confirm({
            select = true,
            behavior = cmp.ConfirmBehavior.Replace,
        }),
` so I found it really weird when trying to run change_choice. Anyway, fingers crossed it's smooth sailing from now on, if not I'll be back with more details :)
