### ISSUE TITLE
Passing the data from an insert node into a child snippet/choice node?

### ISSUE THREAD

**Issue by thorlucas** [L3MON4D3/LuaSnip#245]
I can't seem to figure out how to pass an outer node's `i(n)` values into a child snippet node.

For example, I want to have a snippet that repeats some stuff, then with an optional snippet node inside of a choice. Something like this:

```lua
local class = fmta([[
	---@class <>
	local <> = {<>}

	<>
]], {
	rep(1),
	i(1, 'MyClass'),
	i(2),
	c(3,
		sn(1, fmta([[
			function <>:new(o)
				o = o or {}
				setmetatable(o, self)
				self.__index = self
				return o
			end
		]], {
			rep(1)
		})),
		t''
	),
})
```

In order to generate this:

```lua
---@class Foo
local Foo = {}

function Foo:new()
    ...
end
```

or to optionally skip the function section.

**Comment by L3MON4D3** [comment]
Ah, yes that's a bit rough right now, and I've been meaning to rework that.
You have two options basically, you can use `luasnip.parent_indexer`, but that isn't well tested and may break. To use it, you can just do `rep(luasnip.parent_indexer(1))`. (Might be removed and is a bit of a hack, which is why it isn't documented).
The better, although more verbose, way is using a `dynamicNode` instead of the `sn(...)`, you can just make it depend on the `i(1)`.

**Comment by thorlucas** [comment]
Thanks !

**Comment by L3MON4D3** [comment]
Check out #249, the rework I alluded to in my previous message.
