### ISSUE TITLE
Writing HTML getting foreach snippet

### ISSUE THREAD

**Issue by jrock2004** [L3MON4D3/LuaSnip#262]
With compe and luasnip, if I do something like <div>, I see compe come up with snippet for a foreach. Not sure if this is compe doing this or LuaSnip. 

![image](https://user-images.githubusercontent.com/655716/149623934-d935b446-218d-41ff-a637-41cb96cef5af.png)

Config can be found: https://github.com/jrock2004/dotfiles/blob/main/files/.config/nvim/lua/user/cmp.lua

**Comment by L3MON4D3** [comment]
That could be either `cmp_luasnip` or a snippet from lsp.
If the snippet is in the output of `:LuaSnipListAvailable` you can try removing it from wherever it is loaded. (looks like you're only loading from `friendly-snippet`, are you maybe loading snippets for filetypes other than HTML?)
If it isn't, it's likely coming from LSP, which would be harder to prevent.

**Comment by jrock2004** [comment]
So looking at the output of that command I see things:

```
 }, {
      description = { "For-Each Loop using =>" },
      name = "For-Each Loop using =>",
      regTrig = false,
      trigger = "foreach =>",
      wordTrig = true
    }, {
```

But what's weird is that the is the trigger and what I typed should not show that. I wonder if I should try removing friendly snippets and just make some of my own and see if issue still exists

**Comment by L3MON4D3** [comment]
I think `cmp` shows the snippet because it does fuzzy-search on the completion-items, and finds `foreach =>` for `>`.
AFAICT `friendly-snippets` doesn't have a HTML-foreach snippet, so LuaSnip is probably pulling snippets from filetypes other than HTML (is the `filetype` `html.something`? Do you have a `luasnip.extend_filetypes("html", {something})`?). You could disable that, if you don't really need it, apart from that picking whatever snippets you need from `friendly-snippets` sounds like a good idea :+1:.
`:LuaSnipListAvailable` prints snippets formatted as 
```lua
{
	ft1 = {
		snippet1,
		snippet2
	},
	ft2 = {
		snippet1,
		snippet2
	}
}
```
that way you can tell which filetype provides a given snippet.

**Comment by jrock2004** [comment]
I do not have any luasnip config at all. Going to try to look to see if I should and see if that helps
