### ISSUE TITLE
[Question] How do I assign snippets to keymaps?

### ISSUE THREAD

**Issue by tinny-blueleo** [L3MON4D3/LuaSnip#266]
Hey friends, hope you are well!  Is it possible to insert snippets directly with a keymap.  So with a keymap assign that to auto insert a snippet into the buffer without having to type anything and scrolling the list to enter the snippet?

I have a plugin that lets me assign a Lua function to a keymap.  In that function is it possible to load a snippet from one language conditionally and otherwise load a snippet from a different language?  I write a lot of Svelte code and in Svelte templates you switch between Typpescript, HTML templates, and CSS.  So I'd like to be able to load different snippets for different languages in the same file.

Btw, I'm new to Neovim and this plugin alone makes the switch worth it.  I love it so much!

**Comment by L3MON4D3** [comment]
>  So with a keymap assign that to auto insert a snippet into the buffer without having to type anything and scrolling the list to enter the snippet?

Ouh, nice, yes that's possible: just call something like
```lua
require("luasnip").snip_expand(<snip>)
```
in the function triggered by the keymap where `<snip>` is any snippet, created by ie. `s("trigger", {<nodes>})` or `require("luasnip").parser.parse_snippet("trigger", "a ${1:lsp} snippet$0")`. That will expand the snippet at your cursor.

> In that function is it possible to load a snippet from one language conditionally and otherwise load a snippet from a different language?

I'm not completely sure what you mean by that, could you elaborate?
You can extend filetypes, ie. make luasnip search svelte, typescript, html and css-snippets in svelte files via `require("luasnip").filetype_extend("svelte", {"typescript", "html", "css"})` (be sure to add these extends before loading snippets).

> Btw, I'm new to Neovim and this plugin alone makes the switch worth it. I love it so much!

Really happy to hear that :smile:

**Comment by L3MON4D3** [comment]
>  I was able to get snip_expand working if I create a snippet right before with s().

Nice :ok_hand: 

> I'm loading a bunch of premade snipmate snippets via honza/vim-snippet's plugin. Is there a convenient way to load a particular snippet for a filetype that's preloaded?

No, not really, the function you wrote should work though. If you find that you want to reference lots of snippets by name you could also convert any `ls.snippets.<filetype>`-table into a table where the keys are the snippet names:
```lua
local function convert(snippets)
	local by_name = {}
	for _, snip in ipairs snippets do
		by_name[snip.name] = snip
	end
	return by_name
end

local lua_snippets = convert(ls.snippets.lua)
ls.snip_expand(lua_snippets.forp)
```

that should be faster than searching linearly each time.

> Svelte files have a section for Javascript/Typescript code at the top surrounded by <script> tags. Then in the middle you can do HTML templating with limited control logic.

Luasnip has support for determining the filetype via treesitter instead of just using `&filetype`, if you enable that (and the treesitter-parser for svelte returns `typescript` in `<script>`-tags) you could add the corresponding snippets to `ls.snippets.typescript` or `ls.snippets.svelte` and luasnip should be able to expand them correctly. (Not sure if that actually applies to your usecase, if you always want to trigger the snippets directly and not through `ls.expand()` (eg. via trigger) it won't have any effect).

If you want _the same snippet_ to expand differently depending on context, you'd have to wrap all nodes inside a `dynamicNode`:
```lua
s("for", {
	d(1, function()
		if <in_script_tags> then
			-- can pass 1 here to create a snippetNode
			return ls.parser.parse_snippet(1, "<js/ts-foreach>")	
		else
			return ls.parser.parse_snippet(1, "<svelte-foreach>")	
		end
	end, {})
})
```
But doing those checks before expanding sounds better, then you'd only need to write that check once, instead of once-per-snippet.

**Comment by tinny-blueleo** [comment]
That is amazing, you've answered all my questions.  Thanks for being so helpful and prompt Lemonade, I appreciate it!  Amazing work on the plugin!

**Comment by L3MON4D3** [comment]
Ah, yeah, directly accessing the `ls.snippets`-table is no longer possible, there's some details [here](https://github.com/L3MON4D3/LuaSnip/issues/81#issuecomment-1073301357) (I'd recommend subscribing to/watching the issue :D).
Tt's still possible to get all snippets for some filetype, change `ls.snippets[ft]` to `ls.get_snippets(ft)`.

**Comment by tinny-blueleo** [comment]
How did you get to this question so quickly?  You're one of the fastest maintainers I've ever met.  Thank you this fixed the issue!

**Comment by L3MON4D3** [comment]
You're welcome! 
Your timing was pretty good, I was just done with some work and still had my emails open :D

**Comment by leiserfg** [comment]
We have an alarm with :rotating_light: included :smile:

**Comment by L3MON4D3** [comment]
Hah, that would be amazing xD
(as long as everybody is in one time zone :P)
