### ISSUE TITLE
Dynamically transform inputted text and make the result the new inputted text

### ISSUE THREAD

**Issue by SenchoPens** [L3MON4D3/LuaSnip#282]
Hi, thanks for creating the best Neovim snippet plugin!

I've read the docs, the examples and searched issues, and yet I can't figure if it is possible to create a snippet which will dynamically replace the text I type with the result of a function call.
Example:
I frequently need to type LaTeX matrix rows, they look like `elem1 & elem2 & ... & elem_n \\`. Can I create a snippet `matrix_row`, that will replace a `⎵⎵` (double space) with `⎵&⎵` dynamically (so, the moment I type `⎵⎵`, it gets replaced with `⎵&⎵`).

Or statically, e.g. the moment I enter the 0 input node, the text of the 1 input node gets transformed.

Thank you in advance

**Comment by L3MON4D3** [comment]
Ouh, interesting..
It's possible to enhance `dynamicNode` so that it can depend on nodes that are inside the `dynamicNode` but I'm not certain if it is actually a good idea to do so, as all cases I could think of are better covered in other ways.

For the matrix-snippet, for example
* >the moment I enter the 0 input node, the text of the 1 input node gets transformed

  that's a good idea, luasnip has enter/leave-callbacks ([bit of doc here, look for `callbacks`](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#snippets)) that can be set per-snippet.
It would require accessing some of the internals (getting node-position) of luasnip, but those aren't really subject to change anytime soon as far as I'm concerned
* autotriggered snippet with trigger `⎵⎵`, check if currently inside matrix-snippet, if so expand (downside performance)
  Here you could also use the enter/leave-callbacks to just add and remove the autotriggered snippet if inside a matrix or not.

* use the [dynamic node with user input](https://github.com/L3MON4D3/LuaSnip/wiki/Misc#dynamicnode-with-user-input) from the wiki, it won't work exactly like you described, and would have to be adapted a bit (more input-functions), but it's pretty nice IMO

![](https://user-images.githubusercontent.com/41961280/145810589-f68259a1-a1a6-4e39-87ab-4ab4d7112cc5.gif)

What do you think? Do you have more examples which would really require self-dependent nodes?

**Comment by SenchoPens** [comment]
Thank you very much! The last one looks great, I somehow missed it.
