### ISSUE TITLE
match on 0th node?

### ISSUE THREAD

**Issue by B4rc1** [L3MON4D3/LuaSnip#293]
I want to create a latex snippet which inserts `$|$` and places my cursor where the `|` is.

If I then jump further I want to automatically insert a space if I type a character that is a regular character, not a punctuation or number:
- `$|$` jump + input character: -> `$$ a|`
- `$|$` jump + insert punctuation: -> `$$.|`

I have this working right now:
```lua
s("mk", {
  t("$"), i(1), t("$"), m(2, "[:alpha:]", " ", ""), i(2)
}),
```

My problem is that if I change it to this in order to not have to press jump once more to leave the snippet:
```lua
s("mk", {
  t("$"), i(1), t("$"), m(0, "[:alpha:]", " ", ""), i(0)
}),
```

The snippet will not work anymore. Is there something I'm missing or is this a bug?

**Comment by L3MON4D3** [comment]
Ah, no this isn't a bug: the problem is that `i(0)` does not have the complete functionality of `insertNode`, it only marks the point where the snippet should be left (the specific problem you're encountering here is that the text of the `i(0)` `""`, except if it has default-text(`i(0, "this will be selected after the first jump")`), but the `i(0)` will be empty again after changing that).

You can see the consequence of making `i(0)` a full `insertNode` here

https://user-images.githubusercontent.com/41961280/129266969-149f0a8c-d0bc-43c9-8f5e-a8836e94d589.mp4

(at the end I jumped back into the `i(0)`)
**All** text following the `i(0)` would be inside it because there's no way to exit it.

Your wanted behaviour should be achievable nonetheless, you could utilise the [`callbacks`](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#snippets) snippet-option to register an one-shot autocommand on `InsertCharPre` and change the inserted text (`:h InsertCharPre`) when the snippet is left (maybe for the first time only).

**Comment by B4rc1** [comment]
I got it to work with the `InsertCharPre` autocommand. Thank you very much for the hint :).

This is what I ended up with:
```lua
_G.if_char_insert_space = function ()
  if string.find(vim.v.char, "%a") then
    vim.v.char = " " .. vim.v.char
  end
end
```

```lua
  s("mk", {
    t("$"), i(1), t("$")
  },{
    callbacks = {
      -- index `-1` means the callback is on the snippet as a whole
      [-1] = {
        [events.leave] = function ()
          -- TODO: revisit when lua autocommands api drops
          vim.cmd([[
            autocmd InsertCharPre <buffer> ++once lua _G.if_char_insert_space()
          ]])
        end
      }
    }
  }),
```

**Comment by B4rc1** [comment]
Maybe this should be on the wiki as a recipe/reference?

**Comment by B4rc1** [comment]
I added it to the [wiki ](https://github.com/L3MON4D3/LuaSnip/wiki/Cool-Snippets#all---insert-space-when-the-next-character-after-snippet-is-a-letter).

**Comment by L3MON4D3** [comment]
Ayyy, didn't really expect it to work without issues :D

> Maybe this should be on the wiki as reference?

Yes! It's a great application+demonstration of `callbacks`, thank you for adding it :+1:
