### ISSUE TITLE
option to trim whitespace/indet/newlines with `parser.parse_snippet`

### ISSUE THREAD

**Issue by B4rc1** [L3MON4D3/LuaSnip#294]
with `fmt` I can do:
```lua
  s("def",
    fmt([[
      ```ad-definition
      {1}
      ```
    ]], i(1))),
```
and it expands how I would expect without whitespace in front and without an extra newline with 4 spaces after it.

I expected `ls.parser.parse_snippet` to do the same thing (or at least have an option to) but this:
```lua
  ls.parser.parse_snippet("def", [[
    \\begin{$1}
      $0
    \\end{$1}
  ]]),
```

Expands with whitespace, an extra newline and 2 spaces after it.

**Comment by leiserfg** [comment]
`parse_snippet` has to be able to parse snippets from `lsp` and those don't have the dedent magic, we could add an extra arg to that function to dedent before parsing but the default has to keep the current behavior.

**Comment by L3MON4D3** [comment]
Oookay, `parse_snippet` now has the same default-behaviour as `fmt`, eg. dedent and trim_emtpy set, but this is explicitly disable for snippets coming from `ls.lsp_expand`, which is the only function we've advertised for expanding snippets directly from lsp.
I think that should work just as well, a bit better even since the default-behaviour is more user-friendly.
