### ISSUE TITLE
[bug] parser does not handle escaped `}` correctly

### ISSUE THREAD

**Issue by smjonas** [L3MON4D3/LuaSnip#385]
I have defined the following VSCode snippet:
```json
  "set": {
    "prefix": "set",
    "description": "set",
    "body": "\\{$1\\\\} $0"
}
```

**Expected behaviour:** once the snippet is expanded, `\{ \}` is inserted

**Actual behaviour:** `\{ }` is inserted

**Additional context**: as per the [VSCode grammar](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar), a `}` can be escaped using a backslash, so `\\{` should insert a `{`. The additional two backslashes are used to insert a literal backslash.

To fix it, the body needs to be set to `\\{$1\\\\\\} $0` (6 backslashes which are 2 too many if I'm correct).

**Comment by L3MON4D3** [comment]
Ahh, yup the problem is [here](https://github.com/L3MON4D3/LuaSnip/blob/81b98d204eac7c79974a4273a44901015cba4da4/lua/luasnip/util/parser.lua#L50-L57), resolved (generated from escaped char) chars are again used for escaping other characters.
Normally even `\\{\\}` should work, `}` doesn't _have_ to be escaped, it _can_ :roll_eyes:

**Comment by smjonas** [comment]
Thanks! I think you're right that `}` does not need to be escaped if it's unamibuous but adding an extra `\\` makes it more explicit and works in all cases.
