### ISSUE TITLE
function_node and vim-prettier breaks file

### ISSUE THREAD

**Issue by abenz1267** [L3MON4D3/LuaSnip#455]
Hi,

i'm running into a very weird issue with a snippet of mine:

```lua
ls.add_snippets("typescript", {
    s("litelement", fmt([[
                import {{ html, LitElement }} from "lit";
                import {{ customElement }} from "lit/decorators.js";

                @customElement("{}")
                export class {} extends LitElement {{
                    render() {{
                        return html`<div>{}</div>`
                    }};
                }};
                ]], {
        i(1, "element-name"), create_class_name(1), i(0, "Hello World")
    }))
})
```

and the function for `create_class_name` is:
```lua
local create_class_name = function(index)
    return f(function(arg)
        local name = arg[1][1]
        local parts = vim.split(name, "-")
        parts[1] = parts[1]:gsub("^%l", string.upper);

        if #parts > 1 then
            parts[2] = parts[2]:gsub("^%l", string.upper);
            return parts[1] .. parts[2]
        end

        return parts[1]
    end, {index})
end
```

The problem: as soon as i format the file using vim-prettier, the file breaks like this:

https://user-images.githubusercontent.com/7055955/173055613-f7774989-a910-48f1-978e-223dd7263d74.mp4

As soon as i use a simple insert_node, there's no problem. Formatting via lsp.formatting_sync doesn't break the file.

Anyone got an idea? What's happening here?

Regards

**Comment by L3MON4D3** [comment]
Hah, another manifestation of #129, #174 and #218 (and even though it looks a bit bewildering and funny through sheer unexpectedness, I get it's pretty annoying).

(check those issues for some short explanations)

To fix this: could you set `require("luasnip").session.current_nodes[vim.api.nvim_get_current_buf()] = nil`? While that should  prevent insertion of random text, it's not a perfect fix, the current snippet would lose its interactivity+any history would be gone (which is probably for the best, since their extmarks were moved (worst case, at least))

**Comment by abenz1267** [comment]
setting `require("luasnip").session.current_nodes[vim.api.nvim_get_current_buf()] = nil` didn't help!

**Comment by L3MON4D3** [comment]
Did a quick test, it works for me:

https://user-images.githubusercontent.com/41961280/173186088-f2262216-3e27-405a-a1be-74567f80302b.mp4

Oh, I was too unclear, probably: the current node needs to be set to `nil` between expanding and formatting :sweat_smile:
