### ISSUE TITLE
[Question] Expand snippet from mapping

### ISSUE THREAD

**Issue by idr4n** [L3MON4D3/LuaSnip#456]
I'm sorry if this has already been answered. I just couldn't find an answer to this question anywhere.

Basically, I want to assign a mapping to a particular snippet that has trigger `su`. The snippet has `${VISUAL}` so the mapping should work in visual and normal modes. Something like:

`vim.api.nvim_set_keymap("v", ";s", "<expression to expand 'su' snippet>", { noremap = false, silent = true })`

I wonder if this is possible?

I do have `ls.config.setup({ store_selection_keys = "<c-s>" })` in my config which is quite convenient, but I want a mappings instead for some snippets that I use all the time.

Thanks in advance!

**Comment by L3MON4D3** [comment]
There's a bit of an answer in #389, but for `${VISUAL}` to work, you'd need to insert the `store_selection_keys`-mapping before expanding the snippet, probably with something like this (in practice in lua with `vim.keymap.set`)
```vim
inoremap ;s {expand_snippet, as described in}
" should not call itself, <c-s> enters INSERT 
vmap ;s <c-s>;s
```

(something like that at least, I'm not too sure around noremap/remap)

There might also be subtle issues due to the ;s-function being called through the rhs of a mapping, `vim.schedule`ing the expansion could be a fix in that case.

**Comment by idr4n** [comment]
Thanks, @L3MON4D3. I will try this out.
