### ISSUE TITLE
[Question] Does add_snippets lazy load snippets?

### ISSUE THREAD

**Issue by idr4n** [L3MON4D3/LuaSnip#460]
Hi,

Just a quick question. I'm adding my snippets with `add_snippets` instead of `require("luasnip.loaders.from_<>").lazy_load()`. As my list of snippets grows larger, I wonder if `add_snippets` lazy loads snippets based on filetype and whether Neovim startup performance might be affected if choosing either of the two options.

Thanks in advance!

**Comment by L3MON4D3** [comment]
`lazy_load` works pretty well now, I'd recommend using it just to prevent unnecessary work (why load cpp-snippets when editing html?)

There are situations where you might run into small issues where not all filetypes that can be triggered in a file are actually loaded (example for that in DOC.md, around the loaders-section), but those are all fixable.

Using `loaders` instead of raw `add_snippets` also has other benefits like reload-on-edit and (once it's configured) a quick way to edit the files that contribute snippets to the current buffer via `vim.ui.select` (also described in DOC.md, `filetype_edit` I think)

**Comment by L3MON4D3** [comment]
Oh, and to answer the original question (xD), `add_snippets` does no lazy_loading, it immediately adds the snippets

**Comment by idr4n** [comment]
Great, that's good to know. I will use `lazy_load` instead then. Thanks for answering that!
