### ISSUE TITLE
C++ snippet issue

### ISSUE THREAD

**Issue by ignamartinoli** [L3MON4D3/LuaSnip#477]
The `for`, `while`, `if` and `else if` snippets for **C/C++** have an issue, to put an example, `for` snippet creates the following

```cpp
int main(int argc, char *argv[]) {
	for (range-declaration : range-expression) {
	statements
	}

	return 0;
}
```

when reaching the `statements` section, it is not well indented within the snippet

**Comment by ignamartinoli** [comment]
I'm sending a serie of pics so that it's easier to picture how it goes

![screenshot_20220706190736](https://user-images.githubusercontent.com/103866722/177651680-b309555c-1309-41b4-95bc-65cc084c0039.png)

![screenshot_20220706190739](https://user-images.githubusercontent.com/103866722/177651688-eb28a74e-b2ed-43fc-9bd3-5f9404c48df2.png)

![screenshot_20220706190755](https://user-images.githubusercontent.com/103866722/177651689-a8d83bcf-7536-4668-86a8-b5a7d0ef7011.png)

![screenshot_20220706190758](https://user-images.githubusercontent.com/103866722/177651692-a7c3cf8b-47e9-46ee-97b0-88f3ee734854.png)

**Comment by L3MON4D3** [comment]
Could you figure out if the lsp-snippet even has indent at that position?
Is `:lua require("luasnip").lsp_expand("if\n\tstatement\n")` indented properly? If so, the fault would be with the snippet provided by the language server (probably clangd, or ccls), not with luasnip

**Comment by ignamartinoli** [comment]
Running that command on a **C** file yields

```
if	statement
```

if I understand you, it is indeed indented correctly, should I then open an issue on `clangd` side?

**Comment by L3MON4D3** [comment]
I think that would make sense, at least to ask if there is any purpose in not indenting the statement

**Comment by ignamartinoli** [comment]
I saw [this](https://github.com/clangd/clangd/issues/828) issue there. I really couldn't get it but since its closed it would probably just necrobump. Do you got what that mean or how should I go about that?

**Comment by ignamartinoli** [comment]
Also, I love your profile picture ahahah

**Comment by L3MON4D3** [comment]
> I saw [this](https://github.com/clangd/clangd/issues/828) issue there. I really couldn't get it but since its closed it would probably just necrobump. Do you got what that mean or how should I go about that?

Ouh, yeah that doesn't sound like it'll be changed.
IIUC clangd expects the client to request a format right after this snippet is inserted.
It kind-of makes sense, since there's no guarantee (as far as I know) by snippet-engines that a tab will actually be translated into whatever is used as indent in the file (2/4/8 spaces, for example).
But since clangd is the only (that I know of) language server that does it this way, I'm not sure if it's possible to selectively (only for clangd) always format after a snippet. (additionally, It wouldn't go down well with luasnip at all, since formatting can mess up snippets pretty bad).

I think the easiest solution would be to just not use the lsp-snippets (I think you can blacklist them in cmp at least, via custom comparison, maybe it's even possible through clangd's startup-arguments, that might be nicer), and instead install something like `friendly-snippets` to get some snippets for c++.

You could also modify the snippets received from lsp, there's an example for that [here](https://github.com/L3MON4D3/LuaSnip/wiki/Misc#improve-language-server-snippets). The actual modification would differ quite a bit, you'd have to detect the `item.kind` as `snippet` (I think..) and might get away with just doing `item.textEdit.newText = item.textEdit.newText:gsub("{\n", "{\n\t")` instead of the whole replacement-routine with the global table (if you're not familiar at all with lsp, I'd recommend doing a `print(vim.inspect(item))` in the for-loop of that example, to get a feel for what the completion-items look like)

> Also, I love your profile picture ahahah

Hah, thank you :smile:

**Comment by ignamartinoli** [comment]
Thanks for the help! :-)

**Comment by notfirefox** [comment]
I will leave this here for anyone stumbling on this issue looking for a solution.
```lua
-- variables
local lspconfig = require('lspconfig')
local capabilities = require('cmp_nvim_lsp').default_capabilities()

-- clangd
lspconfig.clangd.setup {
    capabilities = capabilities,
    on_init = function(client)
        local request = client.rpc.request
        function client.rpc.request(method, params, handler, ...)
            if method ~= 'textDocument/completion' then
                return request(method, params, handler, ...)
            end
            local new_handler = function(...)
                local err, result = ...
                if err or not result then
                    return handler(...)
                end
                local items = result.items or result
                for _, item in ipairs(items) do
                    local kind = vim.lsp.protocol.CompletionItemKind
                    if item.kind == kind.Snippet then
                        local text = item.textEdit.newText
                        text = text:gsub('{\n', '{\n\t')
                        item.textEdit.newText = text
                    end
                end
                return handler(...)
            end
            return request(method, params, new_handler, ...)
        end
    end,
}
```
This code is based on the explanation that @L3MON4D3 gave on how to change the snippets.
