### ISSUE TITLE
How to prevent luasnip from jumping to the end of snippet when 0-th InsertNode isn't present in the snippet? 

### ISSUE THREAD

**Issue by AkashKarnatak** [L3MON4D3/LuaSnip#498]
Most of the friendly snippets and emmet snippets does not have a 0-th InsertNode and LuaSnip doc says,
```
If no 0-th InsertNode is found in a snippet, one is automatically inserted after all other nodes
```
Is there a way to disable this feature?

**Comment by L3MON4D3** [comment]
I'm not sure if disabling that is really desirable, the implicit `$0` is also inserted in vscode, and we're trying to emulate it (in that aspect :P), since there are lots of snippets which rely on this behaviour.
Also, a snippet needs to have a `$0`, as a point where the cursor ends up after leaving the snippet.

What's your explicit usecase, maybe we can find a better solution?

**Comment by AkashKarnatak** [comment]
I have set `noselect` for cmp completion and have setup super-tab like mapping for luasnip,

```
    ["<Tab>"] = cmp.mapping(function(fallback)
      if luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      elseif cmp.visible() then
        cmp.select_next_item()
      elseif has_words_before() then
        cmp.complete()
      else
        fallback()
      end
    end, { "i", "s" }),

    ["<S-Tab>"] = cmp.mapping(function(fallback)
      if luasnip.jumpable(-1) then
        luasnip.jump(-1)
      elseif cmp.visible() then
        cmp.select_prev_item()
      else
        fallback()
      end
    end, { "i", "s" }),
```
Since most of the time I don't need to select cmp item, I have given priority to jumps over cmp next item. But in some cases I have ot select cmp item for eg emmet snippets. So when I am working with an html file, the flow goes as follows, `div <Tab>` inserts `div` tag. `p <Tab>` jumps me to the end of `div` snippet. But I want it to complete `p` snippet which does not happen as the cursor jumps to `$0` position of `div` snippet.

https://user-images.githubusercontent.com/54985621/180641117-ba747527-fc84-44e3-b964-96d2c72f9dd9.mp4

**Comment by L3MON4D3** [comment]
Ahh, I see, so `p` is from emmet, not a luasnip-snippet.
The best way to solve this would be to first check what kind of item is currently selected in `cmp`, and
* if it's a snippet,, `cmp.complete`
* otherwise, continue

I correct myself, I think the best solution would be to not overload `<Tab>` with cmp and luasnip. If you're willing to do that, this issue disappears

**Comment by AkashKarnatak** [comment]
I have also setup `<C-j/k>` for cmp but I prefer `<Tab>` over it. Although preselected cmp item is kinda annoying I found removing `noselect` from `completeopt` the best alternative in this case. I can simply press enter key if I want the cmp item. Thank you for your time.
