### ISSUE TITLE
The example in dynamicnode is not working

### ISSUE THREAD

**Issue by zjp-CN** [L3MON4D3/LuaSnip#507]
Hi, I'm learning this plugin, and I find [the code in DOC](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#dynamicnode) is not working:

```lua
local function lines(args, parent, old_state, initial_text)
  local nodes = {}
  old_state = old_state or {}

  -- count is nil for invalid input.
  local count = tonumber(args[1][1])
  -- Make sure there's a number in args[1].
  if count then
    for j = 1, count do
      local iNode
      if old_state and old_state[j] then
        -- old_text is used internally to determine whether
        -- dependents should be updated. It is updated whenever the
        -- node is left, but remains valid when the node is no
        -- longer 'rendered', whereas node:get_text() grabs the text
        -- directly from the node.
        iNode = i(j, old_state[j].old_text)
      else
        iNode = i(j, initial_text)
      end
      nodes[2 * j - 1] = iNode

      -- linebreak
      nodes[2 * j] = t({ "", "" })
      -- Store insertNode in old_state, potentially overwriting older  nodes.
      old_state[j] = iNode
    end
  else
    nodes[1] = t("Enter a number!")
  end

  local snip = sn(nil, nodes)
  snip.old_state = old_state
  return snip
end

...
ls.add_snippets("all", {
  s("trig9", {
    i(1, "1"),
    -- pos, function, argnodes, opts (containing the user_arg).
    d(2, lines, { 1 }, { user_args = { "Sample Text" } })
  }),
})
```
![DynamicNode-example](https://user-images.githubusercontent.com/25300418/182995532-9c720f2c-49f1-4b04-8513-c313b64783d8.gif)

It should change to "2\nSample Text\nSample Text", but actually `2`.

**Comment by L3MON4D3** [comment]
Oh, thank you for bringing that to my attention (and sorry if it's caused any headaches, the documentation should always work :sweat_smile:)
The problem is that `old_text` is no longer used internally, so it always returns its default, `{}`, which produces an error in the `insertNodes` constructor :/

Since that no longer works, and wasn't a good example for dynamicNode from the get-go (it's pretty convoluted for something that's supposed show the basics of dynamicNode), I'll replace it with some other example that shows what `old_state` can be used for
