### ISSUE TITLE
Snippet syntax requires TAB char?

### ISSUE THREAD

**Issue by rodhash** [L3MON4D3/LuaSnip#579]
Hi..

I'm unsure which repo to report / ask this .. but ..

Decided to migrate from vim-snip and while setting up LuaSnip + some custom snippets I faced something weird.. is the `.snippets` filetype requiring a TAB char for identation?

Here a quick vid to better show what I mean:
1. I quickly removed all TABs, the highlight error came up
2. Added a TAB char again for the 2nd block, and things got back to normal for this part

https://user-images.githubusercontent.com/29671981/188353649-eee05fe1-8c69-4ec2-87f2-5f5fec74e2bb.mp4

Or perhaps there's something  we're supposed to tweak / customize for this identation behavior? I tried but didn't find many refs.. 

When the filename is ".snippet" in the singular things work as expected, no snipError highlight poping up .. however the plugin expects the file in the plural and I'm not quite sure why it complains about its syntax ..

I noticed that in the documentation it seems to have a TAB as well:
https://github.com/L3MON4D3/LuaSnip#add-snippets

ps:
- I'm using `v0.8.0-dev+359`, **vl** is jus an alias for vim / lua, a new setup of mine. 
- running latest Luasnip `a45cd5f`

**Comment by L3MON4D3** [comment]
Okay, our general parsing handles indentation other than TAB [just fine](https://github.com/L3MON4D3/LuaSnip/blob/97a51a03c88d91ad928e93105c0198adf784db99/lua/luasnip/loaders/from_snipmate.lua#L36-L41) (we find the first indented line after the `snippet` and remove its' indent from the next lines (requires that all lines are indented with the same characters, otherwise we remove the text (this should be improved)))

The problem is mainly that `syntax/snippets.vim` (highlights lines [not starting with any of `[vsaep\t]` as Error](https://github.com/L3MON4D3/LuaSnip/blob/72ff29a67001d48f849431710a9ed07f0d3de92f/syntax/snippets.vim#L16)) is incorrect, I'll look into changing that.

**Comment by rodhash** [comment]
Thank you very much, working great
