### ISSUE TITLE
Regular expressions with end-of-line match

### ISSUE THREAD

**Issue by weilbith** [L3MON4D3/LuaSnip#592]
Hey 👋🏾 

I'm currently trying to improve my snippets as some of them expand automatically too often when it doesn't fit. Therefore I want to check if there is nothing in the line after the trigger. In theory this should be a simple end-of-line match in the trigger. But that doesn't work. Adding this makes the snippet never expand.

Here is an example. The trigger I was using so far was ` if[%( ]`. So I simply added `$` at the end of the trigger (see below). That doesn't work. To simplify the problem I also tried ` if $`, but doesn't work neither.
Using `^` to match the start of the line works fine for me. No I'm unsure if this has something to do with how regular expressions are matched in the context of LuaSnip or if I don't understand a special case of the Lua expression syntax.

```lua
snippet(
  { trig = ' if[%( ]$', regTrig = true },
  if_node, -- ignore here to a simple example
}
```

Thanks for your help!

**Comment by L3MON4D3** [comment]
Hey!
Soo we currently handle pattern-triggers by
* appending a `"$"` to the trigger
* matching that pattern against the line up to the cursor
([here](https://github.com/L3MON4D3/LuaSnip/blob/3a814e069c73d49887b708417a9f58b948e807da/lua/luasnip/nodes/snippet.lua#L508))
We can't just match the trigger against the full line, because then we'd trigger if

**Comment by weilbith** [comment]
Interesting. So I'll write such a condition.  Should we close the issue then? 🤔 

Talking about `cmp`: how can I list also auto snippets with `cmp`?

**Comment by weilbith** [comment]
To share my simple condition function to anyone who stumbles over this issue:

```lua
local function is_end_of_line(_, trigger)
  local line = vim.api.nvim_get_current_line()
  local match = line:match(trigger .. '$')
  return match ~= nil
end

snippet('trigger', node, { condition = is_end_of_line })
```

@L3MON4D3 there is this [shared module](https://github.com/L3MON4D3/LuaSnip/blob/master/lua/luasnip/extras/expand_conditions.lua) that comes with LuaSnip and only contains a `line_begin` condition. Do you think we should add this function here too? Maybe in a better version if you don't like it.
Which brings me to another question: would it be possible to support a table of conditions which are `and`ed? Like `condition: { line_begin, line_end }`, Now I have to write a wrapper function for every possible combination of conditions I would like to have.

**Comment by L3MON4D3** [comment]
> To share my simple condition function to anyone who stumbles over this issue:
> 
> ```lua
> local function is_end_of_line(_, trigger)
>   local line = vim.api.nvim_get_current_line()
>   local match = line:match(trigger .. '$')
>   return match ~= nil
> end
> 
> snippet('trigger', node, { condition = is_end_of_line })
> ```
> 
> @L3MON4D3 there is this [shared module](https://github.com/L3MON4D3/LuaSnip/blob/master/lua/luasnip/extras/expand_conditions.lua) that comes with LuaSnip and only contains a `line_begin` condition. Do you think we should add this function here too? Maybe in a better version if you don't like it.

Oh yeah, good idea :+1:
I think re-using the passed `line_to_cursor` and checking `#line_to_cursor == #line` would be a tad nicer, would you do a PR for that?

> Which brings me to another question: would it be possible to support a table of conditions which are `and`ed? Like `condition: { line_begin, line_end }`, Now I have to write a wrapper function for every possible combination of conditions I would like to have.

Right, that's useful, though it might be more flexible to do something like this:
```lua
local function and(...)
	local fns = {...}

	return function(...)
		for _, fn in ipairs(fns) do
			if not fn(...) then
				return false
			end
		end
		return true
	end
end

...
condition = and(line_begin, is_end_of_line)
```
Since we could also support other expressions, like `or`.
Exporting those as `require("luasnip.extras.conditions").combinations.<and/or/xor??>` seems like a good option, I'll think about it.

> And btw: what is more cheap/faster: a regex trigger like `{ trig = '^trigger', regTrig = true }` or a `{ condition = line_begin }`?

I think plain trigger + condition should be faster, we have to call the condition, but can avoid the much more general (and therefore slower, I assume) pattern-matching.

**Comment by L3MON4D3** [comment]
> Interesting. So I'll write such a condition. Should we close the issue then?

Let's close it when the new condition is merged, I'd say

> Talking about `cmp`: how can I list also auto snippets with `cmp`?

Ah, not possible :/
There's a PR for that though, you could use that branch

**Comment by weilbith** [comment]
> Oh yeah, good idea +1
I think re-using the passed line_to_cursor and checking #line_to_cursor == #line would be a tad nicer, would you do a PR for that?

Done. #597

> Since we could also support other expressions, like or.
Exporting those as require("luasnip.extras.conditions").combinations.<and/or/xor??> seems like a good option, I'll think about it.

Would be cool to have it out of the box. For the moment I can put into my custom LuaSnip utilities. 👍🏾 

>  think plain trigger + condition should be faster, we have to call the condition, but can avoid the much more general (and therefore slower, I assume) pattern-matching.

Is there a go way to measure this? 🤔 
Maybe this is overengineering, but I'm a bit worried that my dozens of auto snippets could sum up to drop performance over time. So I start to think about what of a snippet impacts its performance. 🙈 

> Ah, not possible :/
There's a PR for that though, you could use that branch

You mean as a result of #513?

**Comment by L3MON4D3** [comment]
> Done. #597 

:ok_hand: 
 

> Would be cool to have it out of the box. For the moment I can put into my custom LuaSnip utilities. 👍🏾

Yes, I agree! I'll look into how to best incorporate them

> Is there a go way to measure this? thinking Maybe this is overengineering, but I'm a bit worried that my dozens of auto snippets could sum up to drop performance over time. So I start to think about what of a snippet impacts its performance. :see_no_evil:

Mhmmm, one thing you could do is start `luajit`s profiler, and just use luasnip for a bit, and then take a look at how much time luasnip takes (Feel free to open an issue for this, too, might be interesting to take a look at performance in the wild, so to say :D)
([using jit-profiiler](https://github.com/L3MON4D3/LuaSnip/pull/315#issuecomment-1047661997))
(although, maybe we need to manufacture a test for this, latency would be more interesting than total runtime..)
If snippets really do take a bit too long, I have some cool ideas to reduce time to look up snippets (sort/store by last trigger-character :wink: Won't apply to pattern-snippets though)

> You mean as a result of #513?

Ah, no, unfortunately not :sweat_smile:
That PR is in `cmp_luasnip`, [here](https://github.com/saadparwaiz1/cmp_luasnip/pull/27)

**Comment by weilbith** [comment]
Talking about performance optimizations and sorting etc. It might be worth to investigate into common conditions. I could imagine that the majority of snippets picks from the same set of conditions. And most of them are snippet agnostic (like begin/end of line, being in a test file, ...). So a mechanism to run such a condition once and then filter all snippets that use this condition could be a great improvement. But keeping this open and extendible by the user (e.g. i could imagine your in-test-file might be different to mine) is a challenge. 

> Ah, no, unfortunately not 😅
That PR is in cmp_luasnip, here

Ah damn. Doesn't look too good.

**Comment by L3MON4D3** [comment]
> Talking about performance optimizations and sorting etc. It might be worth to investigate into common conditions. I could imagine that the majority of snippets picks from the same set of conditions.

Ouh, yeah we could definitely memoize the results of conditions.
The code is [here](https://github.com/L3MON4D3/LuaSnip/blob/8fcf7357d245ae50260e5a7d94e08d1633727fb8/lua/luasnip/nodes/snippet.lua#L516-L568), if conditions are memoized (and therefore pretty quick) we could swap the trigger and the condition.

Not sure if switching is worth it though, checking the trigger is really fast, especially plain triggers.

> Nevertheless, even though some ideas appear to be improvements for sure, it would still require performance measurement tests first. Else everything else is speculation and could be wrong. In worst case make the plugin internals complicated with worse performance.

:+1:

**Comment by atticus-sullivan** [comment]
Well when using fixed (and reused) functions, memoizing should be pretty simple. Make the function a table which (evaluates if necessary and then) returns on `__call` the stored `true/false` (not quite sure, but maybe its possible to even use the table itself as its metatable to reduce the amount of used tables).
This should work in each case the function (which secretly is a table) is used in no matter what context.

The weakness in this approach is, how are we're gonna invalidate the computed results that way?
I can only think this would be possible via some sort of hook which is being run at the end of `match_snippet`, in `snippet_collection` (I guess).
Two issues, first this hook would error if non-memoized functions/tables are being passed (so we'd need to check if the "thing" can/has to be invalidate). And second, we'd need to keep track of the evaluated (and possible memoized) stuff (which isn't that easy in `snippet_collection` as far as I read it).

Regarding logic operators, I consider functions like `and()` always a bit ugly regarding configs as it forces to use prefix operators (which isn't that readable). Maybe making the `&`, `|`, `~` operators (why not if we're already using metatables) would be nicer (thus having infix operators) to read.

**Comment by L3MON4D3** [comment]
> Well when using fixed (and reused) functions, memoizing should be pretty simple. Make the function a table which (evaluates if necessary and then) returns on __call the stored true/false (not quite sure, but maybe its possible to even use the table itself as its metatable to reduce the amount of used tables).
This should work in each case the function (which secretly is a table) is used in no matter what context.

Nice, yes that would work. We already had a similar problem with #535, there we chose to use functions as keys for a table, instead of turning everything into tables with `__call`.
But `__call` is nice here because we wouldn't need to go through that table each time, it's probably the better choice for this :+1:
Also, we could keep the match-code as-is

> The weakness in this approach is, how are we're gonna invalidate the computed results that way?

Yeah, that's a bit hard.
We'd need to know what information the condition depends on, so that might have to specified somehow.
If it only depends on the values passed to it (or buffer-content and cursor-position), a combination of `changedtick` and the expand-position should work nicely.

> And second, we'd need to keep track of the evaluated (and possible memoized) stuff

Couldn't the results be stored in the functions(tables) themselves?

> Maybe making the &, |, ~ operators (why not if we're already using metatables) would be nicer (thus having infix operators) to read.

Ohhh did not know that was possible, would be pretty cool to overload them.

I think we might be able to do this entirely in `extras.conditions` (maybe also a different module), so
* one function to turn `function` into `condition`-object, with memoization and logical operators
  * maybe options for controlling memoization ("buffer", "changes", "cursor", "none", where each option would include the previous ones (so "cursor" would invalidate for a different buffer, different changedtick or different cursor-position))

**Comment by leiserfg** [comment]
The only pain point of using a meta with __call is that it's a bit slower than raw function calls, but I don't know if that will be noticeable in that use case.


> Ohhh did not know that was possible, would be pretty cool to overload them.

That's how the lambdas work more or less.

**Comment by L3MON4D3** [comment]
> The only pain point of using a meta with __call is that it's a bit slower than raw function calls, but I don't know if that will be noticeable in that use case.

Good to know, let's hope it's negligible, I'd really like to make this module independent of the internals :D

>That's how the lambdas work more or less.

Right, I remember :+1:

I think for memoization to really be worth it, and not just be overhead
* we'd need to check the condition before matching the trigger (The probability that there are multiple snippets with a matching trigger _and_ the same, therefore memoizable, condition seems very low (multiple snippets because I assume, most common conditions would have to be computed at least once per expand-call)) (the problem with condition-first is that matching the trigger is probably faster than all conditions, so this would reduce performance for non-memoized conditions)
* the condition would have to be slow to compute, or only depend on eg. the buffer (so it can be effectively memoized)

But adding condition-objects seems worth it for the logical operators alone

**Comment by atticus-sullivan** [comment]
Well we can try to use the profiler to to check if how much the performance difference is (try because it will be hard to create a realistic scenario as everyone uses luasnip a bit differently).

> maybe options for controlling memoization ("buffer", "changes", "cursor", "none", where each option would include the previous ones (so "cursor" would invalidate for a different buffer, different changedtick or different cursor-position))

But then you'd have to store the buffer/curser/... in the condition object as well to be able to check if it has changed, right? (my idea was to invalidate after each completed matching, but you're right it's worth keeping memoization as long as possible)

Actually we should be able to create some memoization factory, so users can create their own conditions which can be memoized (function/memoization object needs of course to be create in advance and has to be shared by the different snippets) :thinking:

**Comment by L3MON4D3** [comment]
> Well we can try to use the profiler to to check if how much the performance difference is (try because it will be hard to create a realistic scenario as everyone uses luasnip a bit differently).

:+1:
If we do create a factory, the decision to memoize or to not memoize could be completely up to the user, might be cool to ship a small script to generate a flamegraph for the regular usage, so one can quickly test what should vs shouldn't be memoized

> But then you'd have to store the buffer/curser/... in the condition object as well to be able to check if it has changed, right?

Yup, fortunately just numbers since we can identify changes by `changedtick` and buffers by `bufnr`, cursor as row,col ofc.

> (function/memoization object needs of course to be create in advance and has to be shared by the different snippets)

Yes :+1::+1:
Those objects could be passed to the snippets, and as long as they behave exactly like functions, which we should be able to do, there are no changes to luasnip itself to accomodate this (which would be really nice, luasnip "core" doesn't need to handle memoization

**Comment by atticus-sullivan** [comment]
Regarding `&`/`|`/`~` metamethods: I might have been too quick on that one (still living in the world of PUC lua5.4 :see_no_evil:). Seems that luajit does not have these metamethods (see [5.1 ref](https://www.lua.org/manual/5.1/manual.html#2.4) and [jit-code](https://github.com/LuaJIT/LuaJIT/blob/1b8d8cabdcc4f1977dc8c51a82074653078d870b/src/lj_obj.h) (hopefully this is the right place, I just searched for metamethod in that repo) or [this (still open) issue](https://github.com/LuaJIT/LuaJIT/issues/63)).

https://bitop.luajit.org/ already announces at least the operators (if there's gonna be metamethods to overload them, no idea :shrug:) but I see nothing of it anywhere else.

I've already seen the use of`*` for `and` and `+` for `or`, but not sure if this is worse than using prefix notation.

**Comment by L3MON4D3** [comment]
Oh that's unfortunate, but I like `+` and `*` :+1:
`-` for not?
Also `==` for XNOR ofc xD

**Comment by atticus-sullivan** [comment]
Just a quick draft with the metatable stuff (no invalidation)

```lua
local memoization_mt = {
    __add  = function(o1,o2) return function() return o1() or  o2() end end,
    __mul  = function(o1,o2) return function() return o1() and o2() end end,
    __unm  = function(o1)    return function() return not o1()      end end,
    __call = function(tab)
        if not tab.mem then
            tab.mem = tab.func()
        end
        return tab.mem
    end
}
local function memoization_factory(func)
    return setmetatable({func=func}, memoization_mt)
end

F1 = memoization_factory(function() return true  end)
F2 = memoization_factory(function() return false end)
F3 = F1 + F2
F4 = F1 * -F2

local m = {F1=F1, F2=F2, F3=F3, F4=F4}
for _,name in ipairs{"F1", "F2", "F3", "F4"} do
    print(name, m[name]())
end
```
(I think memoizing the functions doing the real work should be enough, memoizing some logic operations shouldn't be that expensive (and it gets pretty ugly if we want to deduplicate these ones (inner nodes if you want to think of it as a tree)))
