### ISSUE TITLE
[Feature Request]: Allow user configuration of command used to open snippets with `:LuaSnipEdit`.

### ISSUE THREAD

**Issue by sandersantema** [L3MON4D3/LuaSnip#616]
I'd like to have `:LuaSnipEdit` open the snippets in a new window instead of opening in the current buffer. Currently the way which `edit_snippet_files` opens files is not configurable. For instance:

In `LuaSnip/lua/luasnip/loaders/util.lua`, line 153
```lua
--- Asks (via vim.ui.select) to edit a file that currently provides snippets
---@param ft_files table, map filetype to a number of files.
local function edit_snippet_files(ft_files, edit_method)
  -- Allows configuring the method used to open files but also fallback to default.
  local edit_method = edit_method == nil and vim.cmd.edit or edit_method

	local fts = util.get_snippet_filetypes()
	vim.ui.select(fts, {
		prompt = "Select filetype:",
	}, function(item, _)
		if item then
			local ft_paths = ft_files[item]
			if ft_paths then
				-- prompt user again if there are multiple files providing this filetype.
				if #ft_paths > 1 then
					vim.ui.select(ft_paths, {
						prompt = "Multiple files for this filetype, choose one:",
					}, function(multi_item)
						if multi_item then
							-- vim.cmd("edit " .. multi_item)
							edit_method(multi_item)
						end
					end)
				else
					edit_method(ft_paths[1])
				end
			else
				print("No file for this filetype.")
			end
		end
	end)
end
```

And in `LuaSnip/lua/luasnip/loaders/from_lua.lua`, line 162:
```lua
function M.edit_snippet_files(edit_method)
  -- Allows configuring the method used to open files but also fallback to default.
  local edit_method = edit_method == nil and vim.cmd.edit or edit_method

  loader_util.edit_snippet_files(cache.ft_paths, edit_method)
end
```

Although these modifications would suit my usecase I think it is too hacky as a proper solution and not well suited as a proper PR, hence the issue.

**Comment by L3MON4D3** [comment]
Oh, you can use [`require("luasnip.loaders").edit_snippet_files()`](https://github.com/L3MON4D3/LuaSnip/blob/473eca2e2e269d01b34857f2979e840ebf7ecb6f/lua/luasnip/loaders/init.lua#L22-L70) ([example](https://github.com/L3MON4D3/Dotfiles/blob/b974253b38a53768f5a89e965b4f3b6744f65e5c/.config/nvim/lua/plugins/luasnip/ft_edit.lua#L1-L18)) instead of the version provided by the lua-loader.
Had me confused for a second, I was pretty convinced we had exactly this functionality built-in xD

Not sure why the lua-loader still contains the util-version, might be for backwards compatitbility.
In any case, the doc only mentions the version immediately in `loaders`, so we should be fine :)

**Comment by sandersantema** [comment]
Thanks! Can't believe I missed that one. Can't wait to get to learn luasnip better and use all the functionality of this great plugin :)

If you didn't know about it yet, in the newest neovim version `vim.cmd` is indexed, so you could replace: 
```lua
edit = function(file)
			vim.cmd("tabnew " .. file)
end
```

with: 
```lua
edit = vim.cmd.tabnew
```
Just a bit cleaner :)

I'll close this feature request now.

**Comment by L3MON4D3** [comment]
Oh cool, thanks for the info👍
There are a few places that are ever so slightly restricted by supporting older releases of neovim, might be time to drop them.
