### ISSUE TITLE
Add yasnippet loader

### ISSUE THREAD

**Issue by IllustratedMan-code** [L3MON4D3/LuaSnip#621]
Add support for [yasnippet syntax](https://joaotavora.github.io/yasnippet/snippet-development.html). This would be great for snippet compatibility with emacs. Yasnippet collections [exist](https://github.com/AndreaCrotti/yasnippet-snippets) and could provide a large number of snippets.

**Comment by IllustratedMan-code** [comment]
Only problem I foresee with implementing this is that yasnippets are organized by emacs mode (languages) which would need to be converted to vim buffer types.

**Comment by L3MON4D3** [comment]
Mhmm, maybe.. afaict the snippet-syntax is pretty much just textmate/lsp (which is nice, we'd only need to handle the different package-format), are you aware of differences?

I'm a bit hesitant, because from my pov, we already have a way to load complex snippets (lua-files), and a way to load a simpler syntax (snipmate-collection (which is imo much easier to handle than vscode-packages, but that's beside the point)), so this would fall squarely into "make use of existing snippet collections" (as opposed to "actively write snippets in this"), and for that, an extension to [`snippet-converter.nvim`](https://github.com/smjonas/snippet-converter.nvim) might make the most sense (because then, other snippet-engines only have to be able to parse one of the formats supported by snippet-converter, and can automatically load all the others, getting yasnippets in there seems nice)

**Comment by IllustratedMan-code** [comment]
I wasn't aware of `snippet-converter.nvim`! I agree, a snippet engine agnostic way of dealing with yasnippet is ideal. I'll go over to `snippet-converter.nvim` and make and issue.

Thanks for the speedy reply!
