### ISSUE TITLE
Inquiry for clarification on `autotrigger` in VScode style snippets

### ISSUE THREAD

**Issue by OkelleyDevelopment** [L3MON4D3/LuaSnip#627]
Hello :wave:, I help maintain `friendly-snippets` and was trying to solve [this](https://github.com/rafamadriz/friendly-snippets/issues/189) issue. This led me to testing the following example based on the one provided in the LuaSnip docs:

```json
{
  "example1": {
    "prefix": "options",
    "body": ["whoa! :O"],
    "luasnip": {
      "priority": 2000,
      "autotrigger": true
    }
  },
  "example2": {
    "prefix": "options",
    "body": ["whoa! :O"],
    "luasnip": {
      "priority": 500,
      "autotrigger": false
    }
  }
}
```

When I have the option set to `true` that particular snippet does not show up in the listing. However, when I remove that line _or_ set it to `false` (like in `"example2"`), the custom snippet(s) load and are sorted correctly.

In order to gain some clarity, I checked the following:

- [Issue 268 | Snippet priority discussion](https://github.com/L3MON4D3/LuaSnip/issues/268)
- [PR 334 | Snippet priority implementation](https://github.com/L3MON4D3/LuaSnip/pull/334)
- [PR 514 | auto creating tables discussion](https://github.com/L3MON4D3/LuaSnip/pull/514)
- [LuaSnip Docs | API ref](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#api-reference)
- [LuaSnip Docs on Loaders | VScode](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#vscode)

While I have it working without the line in question, I was hoping to get some additional clarification on what the `autotrigger` line _should be doing_ when set to `true`?

Thanks in advance :smile:

**Comment by L3MON4D3** [comment]
Ohh "the listing" is probably nvim-cmp, and by extension, `cmp_luasnip`, right? That's unfortunate, the snippet works just fine (it should at least :D), it's just not listed by `cmp_luasnip` ([this PR](https://github.com/saadparwaiz1/cmp_luasnip/pull/27) implements it, but it would need some cleaning up, and can't be used right away)
You can use `:LuaSnipListAvailable` (or just manual expansion) to verify snippet-availability (priority-ordering with expansion only, we don't hide "shadowed" snippets, they just won't ever expand)

**Comment by OkelleyDevelopment** [comment]
You're spot on with `nvim-cmp` and `cmp_luasnip` (see picture for specifics) !

![image](https://user-images.githubusercontent.com/56930510/195652407-8e7afc4a-70e0-44e0-b11b-83c4e25e0085.png)

After trying `:LuaSnipListAvailable`, it seems that the `"example1"` snippet above is loaded at the very end of the listing. But when I'm in the editor typing, the popup it's not present which seems to coincide with the PR you linked :mechanical_arm: 

Final question: *what is an autosnippet* compared to a non-autosnippet (is it simply the Lua powered snippets versus the 'text driven' vscode style)?  :thinking:

**Comment by L3MON4D3** [comment]
Nice!
The difference is just that autosnippets are expanded immediately after the trigger is typed:

https://user-images.githubusercontent.com/41961280/195668207-f8529e8e-46fd-42a0-9f1a-c66c885cfdf9.mp4

Can't see it super-well here since keystrokes aren't shown in the video, but I don't have to explicitly `expand` (`<Tab>`) after typing `autotrigger`

**Comment by OkelleyDevelopment** [comment]
Ah I'm finally starting to understand :partying_face:  

This does seem like a very useful feature; if I get some time I might go check the status of/help implement that PR you linked above. 

Thank you very much for the help!

**Comment by DaitiDay** [comment]
Don't know if I should open another issue, but since it's the same problem I'll start here. I have a very similar config (probably the very same) to the one by @OkelleyDevelopment, but even with `autotrigger` set to true the snippet does not get expandrd once the trigger word gets typed.
I do not care about the snippet not being listed by `cmp`, it's just annoying that every snippets with the 'autotrigger = true` do not get expanded automatically (as a matter of fact, I can't expand them at all since they do not do that automatically AND they do not pop up in `cmp`). Is there some options that need to be set in order to get the auto-expansion? Am I missing something?

**Comment by L3MON4D3** [comment]
Oh, yes: you have to pass `enable_autosnippets = true` in `setup`.
eg.
```lua
require("luasnip").setup({
    enable_autotriggers = true
})
```

**Comment by DaitiDay** [comment]
Yeah I have that set in the `opts` dictionary using `lazy.nvim`

**Comment by L3MON4D3** [comment]
I think `opts` only works if there is no custom-function in `config`.
Easiest way to check is to call `setup` manually, like I showed above.

**Comment by DaitiDay** [comment]
Yesssss, now it's working. Thank you thank you thank you! I did not know that about `opts` and `config` ._.

**Comment by L3MON4D3** [comment]
Yeah, that's not really obvious.
Glad it works! :)
