### ISSUE TITLE
Applying `extend` to the `edit_snippet_files` function fails

### ISSUE THREAD

**Issue by dhazel** [L3MON4D3/LuaSnip#648]
## Meta:
* OS: Windows
* Neovim version: 0.8

## Description:
When applying `extend` to the `edit_snippet_files` function, as described in the readme [at the bottom of the edit_snippets section](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#edit_snippets), neovim is throwing an error.

The code from my `init.lua` (line numbers included):
```
171 -- Luasnip snippet editing
172 require("luasnip.loaders").edit_snippet_files {
173     extend = function(ft, paths)
174         if #paths == 0 then
175             return {
176                 {
177                     "CONFIG/snippets/" .. ft .. ".snippets",
178                     string.format(
179                         "%s/%s.snippets",
180                         vim.env['HOME'] .. "/.config/nvim/snippets/",
181                         ft
182                     )
183                 }
184             }
185         end
186
187         return {}
188     end
189 }
```

## The error:
```
Error detected while processing [redacted...]\AppData\Local\nvim\init.lua:
E5113: Error while calling lua chunk: ...site\pack\packer\start\LuaSnip/lua/luasnip/util/util.lua:484: attempt to index local 'config' (a nil value)
stack traceback:
	...site\pack\packer\start\LuaSnip/lua/luasnip/util/util.lua:484: in function 'get_snippet_filetypes'
	...e\pack\packer\start\LuaSnip/lua/luasnip/loaders/init.lua:40: in function 'edit_snippet_files'
	[redacted...]\AppData\Local\nvim\init.lua:172: in main chunk
```

**Comment by L3MON4D3** [comment]
Hi, thanks for the report.

I can't reproduce this error, which is weird because it seems to me that this should not depend on any configuration ([error originates here](https://github.com/L3MON4D3/LuaSnip/blob/22b7c117de19a8de815823e5c32cbbd551d0cd10/lua/luasnip/util/util.lua#L483-L484))

Does just `:lua = require("luasnip.session").config` also throw an error?

Ahhh, or is the `setup`-call missing? `require("luasnip").setup()` should do it in that case

**Comment by dhazel** [comment]
Yep. Thanks!

The `require("luasnip").setup({})` call was missing.
