### ISSUE TITLE
[Question] How would I replace placeholder text if untouched?

### ISSUE THREAD

**Issue by JxJxxJxJ** [L3MON4D3/LuaSnip#732]
Placeholder text is useful since it helps me to know _what goes where_ but there are times I want *only* that. 

For example in: 

```lua
s(
  {
    trig = ";qs",
  },
  fmt(
[[
\qs{<>}{<>}

<>
]],
   { -- Nodes
      i(1, "Name:"),
      i(2, "Content:"),
      i(0),
 },
{ -- <> as delimiters
delimiters = "<>"
}
)
)
```
Sometimes I want to leave ":Name" blank, leaving something like `\qs{}{<>}`, how would I achieve that? What am I looking for in the docs?

**Comment by L3MON4D3** [comment]
That could be done via the `leave`-event, check the code at the bottom of [this comment](https://github.com/L3MON4D3/LuaSnip/discussions/674#discussioncomment-4253227) for an example (mainly parseReturns, it could be adapted to suit your purposes)

**Comment by L3MON4D3** [comment]
> I see, something like [events.leave] = myFun where myFun does the checking? 

Yes, exactly

> How could I dinamically say: check if in i(1, "X") if what is typed in <> is "X" then do something?

The I guess canonical way to do something like this is `dynamicNode`/`functionNode`, where they depend on the `i(1)` and check if the `i(1)` contains `"X"`, but it's not possible to have the dynamicNode depend on itself (would create a kind of feedback-loop, and I don't know how to properly deal with that), which would be required for the scenario you mention above.


Oh one last thing: once neovim has support for [anticonceal](https://github.com/neovim/neovim/pull/9496) this `what goes where`-usecase could be achieved (more idiomatically, since there's then a distinction between "I want this as default-text" and "I want to remember what to put here") by giving unvisited nodes some inline virtual text via [`ext_opts`](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#ext_opts).

**Comment by JxJxxJxJ** [comment]
Thanks for the answers. 

I believe it'll be easier to "delete `"X"` after entering". But now, how do I modify the text of a node from a callback? I have something like this 

```lua
return {
  s(
    { -- Params
      trig = ";preg",
      dscr = "Inicia el question environment",
      regTrig = false,
      priority = 1000,
      snippetType = "autosnippet",
    },
    fmt(-- Format
    -- String of text
      [[
\qs{<>}{<>}

<>
]]     ,
      { -- Nodes
        i(1, "Name:"),
        i(2, "Content"),
        i(0),
      },
      { -- <> as delimiters
        delimiters = "<>"
      }
    ),
    { -- Callbacks
      callbacks = {
        [1] = { -- Name
          [events.enter] = function()
            local fun

          end,
        },
        --   {
        --     [2] = { -- Content
        --       [events.leave] = myCheck,
        --     },
        --   },
      },

    }),
}
```

**Comment by L3MON4D3** [comment]
The callback [receives the node as an argument](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#events), with that you can get the position occupied by the node in the buffer (wait for #740 to be merged and call `node:get_buf_position`, or use the [implementation](https://github.com/L3MON4D3/LuaSnip/pull/740/files#diff-b07d93bd6f81a70f19cefae157b41475be5eb7fc0474f4118feb52c803deb78dR391-R400) directly for now (you'll want the `raw=true`-variant)), and delete text there with `nvim_buf_set_text` (set to empty string).
