### ISSUE TITLE
[Feature Request] Add the ability to show a `sign` instead of virtual text

### ISSUE THREAD

**Issue by utilyre** [L3MON4D3/LuaSnip#787]
So I just configured the virtual text to be shown whenever I enter a choice node, however it'd be more natural to me to see that info (being in choice mode) in the `signcolumn` as a sign.

I thought it'd be great to have this option in addition to `hl_group` and `virt_text` in `ext_opts`.

Just a quick suggestion, here's how I'd expect the default config be:

```lua
  {
    ext_opts = {
      [types.choiceNode] = {
        active = {
          sign = "LuasnipSignChoiceNode", -- and LuasnipSign[node] for other node types
        },
      },
    },
  }
```

Many thanks for this awesome plugin!

**Comment by L3MON4D3** [comment]
I agree, that's a nice feature!
It would be very hard (or at least not very elegant) to implement it with `ext_opts` though, since we get those effectively for free from extmarks (check `:h nvim_buf_set_extmark`, the `opts`-argument).

What could work, is adapting the [choiceNode popup](https://github.com/L3MON4D3/LuaSnip/wiki/Misc#choicenode-popup) from the wiki to not open a window, but place a sign. If you have some experience with the vim-api and lua, this seems like a nice exercise :P

**Comment by utilyre** [comment]
Thanks! I got it working with the following code in case anyone wants this as well:

```lua
  vim.fn.sign_define("LuasnipSignChoiceNode", {
    text = "",
    texthl = "LuasnipChoiceNode",
  })

  local group = vim.api.nvim_create_augroup("config.plugins.luasnip.choice", {})
  vim.api.nvim_create_autocmd("User", {
    group = group,
    pattern = "LuasnipChoiceNodeEnter",
    callback = function(a)
      vim.fn.sign_place(
        0,
        "config.plugins.luasnip.choice",
        "LuasnipSignChoiceNodeActive",
        a.buf,
        {
          lnum = vim.api.nvim_win_get_cursor(vim.api.nvim_get_current_win())[1],
        }
      )
    end,
  })
  vim.api.nvim_create_autocmd("User", {
    group = group,
    pattern = "LuasnipChoiceNodeLeave",
    callback = function(a)
      vim.fn.sign_unplace("config.plugins.luasnip.choice", {
        buffer = a.buf,
      })
    end,
  })
```
