### ISSUE TITLE
nested snippet are not visually selected

### ISSUE THREAD

**Issue by otavioschwanck** [L3MON4D3/LuaSnip#795]
Snippet:

```
  "letm": {
    "prefix": "letm",
    "body": "let(:${1:model}) { create(:$1${2:, ${3:}}) }$0",
    "description": "let(:model) { create(:model, ...) }"
  }
```

When it goes to 2, instead of selecting 3, it just enter in insert mode.

![snippet](https://user-images.githubusercontent.com/9551316/221435739-e327665c-7e6c-4558-a3d6-e17cfbb8647b.gif)

**Comment by L3MON4D3** [comment]
Yes, that's not the default-behaviour.
Check the wiki, I wrote a function to recreate the vscode-behaviour. Might no longer work though..

**Comment by otavioschwanck** [comment]
it worked, should be default (and improved)!  Thanks for your help

**Comment by L3MON4D3** [comment]
True, maybe it should be the default.
I'm hesitant to do so since 
* It's less "luasnip", the default is to replace it with a choiceNode which has an empty insertNode and the snippet, and this is much more reliable than the rather hackish implementation of the selection (though the hackish-ness could be less bad if we ensured its behaviour with tests)
* I don't want to spend a breaking change on it (changing defaults would have to be one)

OTOH the selection is visually much nicer.. Maybe I'll do a big breaking change sometime, where other defaults (`{delete,region}_check_events`) are also changed.
