### ISSUE TITLE
problem when reusing insert nodes with default text

### ISSUE THREAD

**Issue by max397574** [L3MON4D3/LuaSnip#816]
I got this function
```lua
local function reuse(idx)
    return f(function(args)
        return args[1][1]
    end, { idx })
end
```

so I can just do e.g.
```lua
s("beg", {
    t("\\begin{"),
    i(1),
    t({ "}", "" }),
    i(0),
    t({ "", "\\end{" }),
    reuse(1),
    t("}"),
}),
```
(latex snippet)

this works just fine

https://user-images.githubusercontent.com/81827001/224263809-7dc83bf8-375e-4d20-8141-006795773bf0.mov

however when I add a default text to the insert nodes like this:
```lua
s("beg", {
    t("\\begin{"),
    i(1,"test"),
    t({ "}", "" }),
    i(0),
    t({ "", "\\end{" }),
    reuse(1),
    t("}"),
}),
```
https://user-images.githubusercontent.com/81827001/224264244-85ee5cca-5e35-4985-965d-2cf784f2e82a.mov

**Comment by evesdropper** [comment]
Also not exactly a solution, but you could use `extras.rep` instead of a function node - for instance, here is my implementation of the same snippet.

```lua
s(
    { trig = "beg", name = "begin env", dscr = "begin/end environment" },
    fmt([[
    \begin{<>}
    <>
    \end{<>}]],
    { i(1, "test"), i(0), rep(1) },
    { delimiters = "<>" })
),
```

**Comment by max397574** [comment]
> Weird, what's your `update_events` set to?

"TextChanged", "TextChangedI", "InsertCharPre"

**Comment by L3MON4D3** [comment]
Okay, I could reproduce the issue: it's due to `InsertCharPre` - `textlock` is active so we're not allowed to change the buffer, but `update_events` can (most likely will) cause just that

Basically, `update_events` can't contain `InsertCharPre`. To prevent this issue, we could add a warning if it is passed in `setup`.

Not sure what went wrong in your tests @evesdropper, are you sure the changed config was actually effective?
