### ISSUE TITLE
Optional Arguments

### ISSUE THREAD

**Issue by EmperorEntropy** [L3MON4D3/LuaSnip#821]
Hello! I have a question regarding the possibility of optional arguments with LuaSnip. I apologize if something like this has been asked before, but I couldn't find anything similar.

I am writing a LuaSnip for the LaTeX `\sqrt{}` function, and I was wondering if it is possible to specific an optional part of the snippet that is removed if I don't enter anything in it. For example, when I type `sq`, I want the letters to auto-expand to `\sqrt[]{}` where the cursor is between the `[]`. If I hit Tab, the cursor jumps to `{}`, and `[]` disappears since I didn't type anything in it. Otherwise, if a type a number and then hit tab, `[]` with the number stays, and the cursor moves to the inside of `{}`.

Is this accessibility supported by LuaSnip? If so, how can I write a snippet that does this?

Thank you!

**Comment by L3MON4D3** [comment]
Yes, that's possible: use functionNodes for `[` and `]`, but they only insert if $1 is empty.
If you want to do it a bit more idiomatically, you can use [match](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#match)

**Comment by EmperorEntropy** [comment]
Thanks for the reply! I looked at the documentation for functionNodes, but I found it very confusing, so I'm not exactly sure what you meant by inserting the brackets only if $1 is empty. I use fmta to write my snippets, so I have no idea with $1 means. Is it the first <>? If so, shouldn't the brackets only insert before and after it if it is not empty? I want the brackets to exist if a type in a number. Otherwise, I skip to the next <>, and the brackets should not exist. How would I precisely create a function that does that? Thanks again.

**Comment by L3MON4D3** [comment]
So right now the [] appear exactly if you put a single digit into i(1), right?
Having them appear initially, and the disappear is a bit more difficult because it's only easy to do these updates when text changes, and not on jumping around in the snippet.
You can somewhat work around this with events, basically callbacks, in lua, which can for example be run when a node is left (which we'd like to detect here).
Essentially, set some variable upon leaving the i(1), and check that variable in the functionNode (you'd have to replace the match with it, because this can't be implemented with match)

Alternatively, and I think this is a bit better (much more straightforward), use a choiceNode to switch to/away from the `[]`. It's one more key press, but I wouldnt worry about that too much

**Comment by EmperorEntropy** [comment]
Thanks for your feedback! In that case, I think my current method works the best. Choice nodes do seem interesting, but hitting Tab is faster for me than Ctrl n, especially on a Mac. I'm still relatively new to LuaSnip, but I'm already greatly impressed by its functionality. I can't wait to learn more about it! Thanks again!

**Comment by L3MON4D3** [comment]
> Thanks for your feedback! In that case, I think my current method works the best. 

I'd agree there :D

> I can't wait to learn more about it! Thanks again!

Awesome, you're welcome :)
