### ISSUE TITLE
Better reference system

### ISSUE THREAD

**Issue by Entoryvekum** [L3MON4D3/LuaSnip#827]
In complecated snippets (like snippet for matrixs and tables), we often use dynamic node to generate the snippet depending on the input. In the matrix case, I implemented a snippet which add the seperator '&' when typing tab key and generate a new line when \\ is detected. I want to add new collumn in every row automaticly when a new collumn is added in a specific row  but such dynamic generation lead to a great difficulty in node reference. 

I suggest provide proper pointers to reference the node.
1. the pointer should be able to do treewalk
2. provide proper invalidation mechanism when dynamic node reevaluation change the structure of nodes
3. trigger function node or dynamic node reevaluate manually ( which simplify the implement of external update dynamic node )
4. modify the information in insert node and text node ( reduce the use of dynamic node )

**Comment by L3MON4D3** [comment]
Whew, okay that's pretty wild..
Yeah, update_dynamic_node is well suited for that task :+1:

Okay, related (to named nodes) idea: generalize from names to keys (ie. numbers, strings,... anything that can be key in a lua-table). Then you could use integers to address the desired nodes (although, this would also fail as soon as two such structures are desired inside one snippet). I guess it would be best to allow a hybrid-approach (address children of some node, get that node by name), since address-by-key can become cumbersome when many keys are required, and address-by-position (i.e. expose tree structure+walker) can become annoying if the snippet is deep, or changes a lot.

Unfortunately (well, for your usecase), dynamicNodes always generate new nodes, so the old ones always have to be invalidated.

sidenote: One pretty cool functionality which can't be really achieved right now (well, it can, but not comfortably) is preserving the cursor-position (this is possible if restoreNodes are used, but they don't support all of what you want to do). We'd need an api to determine the node that should be entered, in the new snippet.
May not be totally useful, but sounds like it would give it that little something :D

**Comment by Entoryvekum** [comment]
> I guess it would be best to allow a hybrid-approach (address children of some node, get that node by name), since address-by-key can become cumbersome when many keys are required, and address-by-position (i.e. expose tree structure+walker) can become annoying if the snippet is deep, or changes a lot.

Can't agree more. And i believe i can't replace something like `ls.session.current_nodes[vim.api.nvim_get_current_buf()]` and even improve the snip argument for function node!

> Unfortunately (well, for your usecase), dynamicNodes always generate new nodes, so the old ones always have to be invalidated.

I understand your point. If we need a dynamic node that doesn't change the structure, we could just use a snippet node :)

I admire your passion to this plugin, and I'm eager to particiate the development. But as I don't have any experience in developing such big project, it will take a long time for me to get hands on.

**Comment by L3MON4D3** [comment]
Had some time, looked into it a bit, check #838.
I think the second example should contain all the bits you need to create the matrix-snippet, right?
(`node:get_text` is not officially api yet, but that will also happen as soon as I get to it)
