### ISSUE TITLE
Postfix with VSCode format?

### ISSUE THREAD

**Issue by andresatierf** [L3MON4D3/LuaSnip#840]
Is there a way to create a postfix in the vscode files format?

**Comment by evesdropper** [comment]
To my knowledge, that depends on the features that VSCode snippets have.

**Comment by L3MON4D3** [comment]
It's possible to use [the postfix-snippets from extras](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#postfix-snippet) with parsed/lsp-snippets with

```lua
postfix(".par", parse(nil, "($POSTFIX_MATCH)"))
```

(Passing `nil` as the first argument to `parse` (aka `ls.parser.parse_snippets`) will just return a flat list of nodes)

Unfortunately, this is not possible from the vscode-loader, and I think it's reasonable to require lua-snippets for this (see [here](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#lua) for some guidance in setting up the lua-loader, otherwise you can just call `require("luasnip").add_snippets("all", {<snippets here>})` somewhere in your lua-config)
