### ISSUE TITLE
Repeat node breaks when snippets are applied

### ISSUE THREAD

**Issue by RobinTruax** [L3MON4D3/LuaSnip#859]
I haven't been able to find a hack for this, and to me it seems like very natural behavior. Suppose, for a minimal example, that I want to write a piece of text twice -- say the trigger is 'trig', and the nodes are `{i(1), rep(1)}`. Now, suppose that I have another snippet which automatically expands `rr` to, I don't know, `radio`. The problem that I'm running into is that I would love to trigger my repetition snippet, type `rr`, and have `radio` appear in both places. However, this isn't what happens: `rr` appears in the second snippet, and furthermore it stops updating whatever I type in the first insert node. This seems like suboptimal behavior in general, as well as being an issue for my particular use case. Is there a solution for this? If not, it seems like a meaningful feature to add.

**Comment by leiserfg** [comment]
Putting another snippet in an input won't work, but you can achieve the same behavior (for simple cases like the rr to ratio) with abbreviations.

**Comment by L3MON4D3** [comment]
Ohhhh true, that's a limitation we currently have!

That is because we do update the parents of the current node, but this is limited to the snippet the node belongs to.

We could just check if the snippet is inside another snippet (not by querying the positions of all snippets in the buffer, I think that would take too long, but by just checking the pointers we set to jump from a nested snippet back into the outer one) and then update that one too, but this is not completely reliable (the "logical" snippet-structure does not necessarily correspond to the way the snippets are laid out in the buffer)

To make it work perfectly, we'd have to make sure the snippets are inserted into the logical tree corresponding to their layout in the buffer (maybe we should have done this a long time ago, it might actually fix lots of those "jump back somewhere else in the buffer"-issues :sweat_smile:)

**Comment by L3MON4D3** [comment]
Fixed by 64bf87a :tada:
