### ISSUE TITLE
BUG: Pressing TAB in an unfilled field causes undocumented behaviors

### ISSUE THREAD

**Issue by Zeioth** [L3MON4D3/LuaSnip#908]
I have the next snippet:

```
  "returns": {
    "prefix": "<returns>",
    "body": [
      "/// <returns>description.</returns>$0"
    ],
    "description"Irrelevant"
  },
```
Every time I press TAB, the snippet prints:

    text.</example>

On the buffer, instead of exiting the snippet. There is a way to prevent this? I just want the snippet to print

    /// <returns>text.</returns>

**Comment by Zeioth** [comment]
I think it is a bug, because if I actually write something before pressing TAB the issue doesn't manifest.

**Comment by L3MON4D3** [comment]
I guess the snippet is just expanded again and again because the text before the cursor matches itself :/
You can work around this issue by either
* making sure there is no place to jump from where the text before the cursor matches some trigger
* Just use different keybindings for jumping and expanding (I'm doing this one, it's working really well imo)

**Comment by Zeioth** [comment]
Either for a cmp update or a change on my personal mappings, the issue is gone.

**Comment by Zeioth** [comment]
* The first workaround doesn't work on my end
* The second does 👍

**Comment by L3MON4D3** [comment]
Yeah, 1) is pretty hard to maintain unfortunately :/
I'm going to close this, I don't think there's any other solution
