### ISSUE TITLE
History still enabled even when set to false?

### ISSUE THREAD

**Issue by jghauser** [L3MON4D3/LuaSnip#91]
I'm not sure whether I'm misunderstanding something or whether this is a bug.

With the default settings, history is disabled as I understand. However, even in this case, I seem to be able to jump back into past snippets if I have left them before arriving at the last node. I have enabled the supertab-like feature, which leads to me often jump halfway across a file when I least expect it.

What I would like to happen is that as soon as my cursor isn't inside the snippet anymore, I can't jump back to the snippet. I think this was the default behaviour with ultisnips.

Also, thanks a lot for this plugin, it's so much more flexible than all the alternatives!

**Comment by L3MON4D3** [comment]
Ahh, yeah that's the expected behaviour. The snippet you expand is, as far as luasnip is concerned, a child of the outer snippet. `history` only makes it so that it's not possible to reenter snippets that have already been left.
But I definitely see the need for another option to leave snippets when leaving their 'textual space', I'll think about how to get that right.

**Comment by jghauser** [comment]
Thanks for the explanation, I would definitely appreciate such an option :)

**Comment by L3MON4D3** [comment]
Hey, you can now achieve ultisnips' behaviour (or at least something close) by setting `region_check_events` to `'CursorMoved'` or `'CursorHold'` and `history` to `false`, please check if it works for you.

**Comment by jghauser** [comment]
Seems to work perfectly, thanks! I'm closing the issue now as i think this has been resolved. If I come across any odd behaviour, I'll get back to you.
