### ISSUE TITLE
[Feature] passing `matched_trigger` and `captures` to `show_condition` like `condition`

### ISSUE THREAD

**Issue by Bekaboo** [L3MON4D3/LuaSnip#931]
Hi, thanks for all your work on LuaSnip!

This is a actually a minor issue, but is it possible to pass `matched_trigger` and `captures` to `show_condition`? The reason why I want this is because currently there's no convenient way to detect if a snippet with `regTrig=true` can be expanded in the `show_condition` callback, consider the following snippet:

```lua
s({ trig = '(%w+)test', regTrig = true }, {
  f(function()
    -- do some stuff...
    return ''
  end, {}, {}),
}),
```

Currently an completion entry to the snippet above will be shown if the cursor is after a parenthesis:

![image](https://github.com/L3MON4D3/LuaSnip/assets/76579810/f57776f8-bf18-4b99-a443-3cd7d22319a2)

which is undesired since the snippet is intended to be expanded after alphanumeric characters.

A direct solution is to add the attribute

```lua
show_condition = function(line_before) --[[ return true if line before cursor matches (%w+test) ]] end
```

but it is cumbersome to write a different `show_condition` callback for each snippet with a regex trigger.

If the `show_condition` callback accepts `matched_trigger` or `captures` just like `condition` callback do, one can simply check the `matched_trigger` and return false if `matched_trigger` is `nil` or an empty string, then register a new snippet like this:

```lua
local s = ls.extend_decorator.apply(ls.snippet, {
  show_condition = function(_, matched_trigger, _)
    return matched_trigger and matched_trigger ~= ''
  end,
})

-- define new snippets using `s`...
```

---

A even better way I can think of is to add a new option `show_only_when_expandable`, which automatically sets `show_condition` to the same functions as `condition` for snippets with normal triggers and sets `show_condition` to a function that returns true when the text before the cursor is expandable (e.g. `condition` returns `true` and text before matches the regex trigger) for snippets with regex trigger.

**Comment by L3MON4D3** [comment]
Hmmm yeah, `show_condition` is a bit restricted, and your usecase is quite nice...
`show_only_when_expandable` sounds like a nice idea, but I think I'd like to put its implementation into the user-side of things (for more flexibility), ie. provide api for determining whether the snippet matches some text (and retrieving the captures if it does).
If the `show_condition` also receives the snippet ( <-would require some refactors/soft-deprecations, but nothing I'm unwilling to do :D ), this could be implemented pretty easily.

One remaining issue is that `cmp_luasnip` (I'm assuming you're using that) can't expand snippets with non-plain triggers (by default) since it doesn't detect whether the string in front of the cursor currently matches the snippet, so that would also need some thought/modifications.

Are you actually expanding the regTrig-snippet via cmp, or are they just polluting your results?

**Comment by Bekaboo** [comment]
Thanks for your reply!

> Are you actually expanding the regTrig-snippet via cmp, or are they just polluting your results?

In most cases I use cmp just to trigger snippets provided by language servers, for self-made snippets I simply hit `<Tab>` to expand them, so yes, the completion entries of the regex triggers are just polluting the results.

**Comment by L3MON4D3** [comment]
> so yes, the completion entries of the regex triggers are just polluting the results.

Yeah alright.. I think in that case it makes most sense to just set `hidden` on those snippets, they shouldn't show up at all with that.

> Yeah I also noticed this, it will be great if there's a way to expand snippets with regex triggers using cmp, although in most cases I just use <Tab> to expand them.

The idea with the pattern-expansion is that we expand a helper-snippet where all groups of the trigger can be filled in, which I think fits the usecase of cmp pretty nicely, but obviously somewhat gets in the way of using cmp as a replacement for regular expansion (which also doesn't really make sense)

If you're happy with setting `hidden` (via extend_decorator ofc :D), for your specific issue, we should close this, and I'll create another issue for extending show_condition in the way I described earlier (I'm sure this may come in handy, but it's not pressing, more like a nice to have)

**Comment by Bekaboo** [comment]
Sounds reasonble to me, thanks for your suggestion!
