### ISSUE TITLE
Bug - Lua pattern matching don't work at first time

### ISSUE THREAD

**Issue by Dioprz** [L3MON4D3/LuaSnip#976]
Hello!

I want to report a behavior that I found strange when declaring the following snippet:

```lua
  s({
    -- trig = "h([1-9])",
    -- trig = "h(%d)",
    name = "insert header",
    trigEngine = "pattern",
    -- regTrig = true,
    },
    {
      f(function( _, snip)
        print(snip.captures[1])
        return string.rep("=", snip.captures[1])
      end, {})
    }
  )
```

What happens is the following:

- If I use the trigger `h([1-9])` the snippet works perfectly for any number between 2 and 8. However, when I do `h1<tab>`, it throws an error and prints nil. The strange thing is that if I do it again, this time it works without problems.

- If I use the trigger `h(%d)` instead, everything works without problems.

Is there any reason for this behavior? Is there something I'm not seeing/configuring properly?

Thank you very much for your work on this plugin, I'm fascinated to discover what I can do with it!

**Additional note**: I have also found a strange behavior with the trigger "h([1-9])" when I exchange the key `trigEngine = "pattern"` for `regTrig = true`. When doing so, if I type `h1<tab>` the snippet directly does not work and shows the text `h[1-9]`, but if I press enter, it just jumps to the next line and in the previous line there is an "h" left. It also works fine for digits between 2 and 8. On the other hand, using the pattern "h(%d)", everything works correctly. 

I think the `trigEngine` and `regTrig` options are confusing if `trigEngine` uses `pattern`; could you please explain me what is the difference? I saw that you are interested in deprecating `regTrig` (https://github.com/L3MON4D3/LuaSnip/pull/923). If you would like to update the documentation and examples, let me know and I think I can do a PR!

**Comment by L3MON4D3** [comment]
Hi!
Ah, you're probably triggering via nvim-cmp, right?
That does not yet work with `trigEngine=pattern`, it has to be updated to recognize that it is dealing with a pattern :/
If you additionally set `regTrig=true` it will work (because cmp_luasnip knows how to handle that, and it is equivalent to `trigEngine="pattern"`), but this is obviously only a temporary fix.

>  I have also found a strange behavior...

Yeah, that's a workaround for dealing with regTrig-snippets:
If a pattern with captures is expanded via nvim-cmp, we don't have any values for the captures (because the expansion was not typing a trigger, but selecting that snippet).
This means we cannot meaningfully expand the snippet, because there might be implicit assumptions about the trigger (for example `(%d%d).(%d%d).(%d%d%d%d)` is the trigger for a date, and if we just insert some default-values like 0 for each capture, it doesn't really make sense) wich could lead to errors (a capture is assumed to be a number, and we can't detect that if the pattern just contains a `.` at its place).
So instead, we expand a helper-snippets whose function it is to indirectly prompt the user to enter values for the used captures, and after jumping to its end, it can be expanded manually (as long as the provided data actually match the trigger)

There also isn't already a solution for the nvim-cmp-problem because I can't think of a maintainable way of implementing this helper for other trigEngines, like full-blown regex, where that helper-snippet would have to be very complicated.

**Comment by Dioprz** [comment]
Oh, okay, that makes a lot of sense. And yes, I'm doing it with nvim-cmp, and everything worked just as you mention.

In case it might be useful to anyone, the snippet does continue to be usable (in both cases), you just have to know how to run it:

1. If you use the `trigEngine="pattern"` option WITHOUT `regTrig=true`, just let it fail the first time with the endpoints (i.e. `h1<tab> -> error`), and from then on the snippet updates and works flawlessly for subsequent calls.

2. If you use `regTrig=true` with or without `trigEngine="pattern"` (I didn't notice any difference when enabling it), then the way to make the snippet work on the extreme values is: `h1<tab>1<tab>`. That is, re-enter the value to be captured.

In any case using the `(%d)` capture instead of `([1-9])` works uneventfully, as I mentioned, but for cases where it can't be evaded, the first option is certainly more practical.

Thank you very much for your time and explanation, if you consider so, you can close the issue!

**Comment by L3MON4D3** [comment]
Nice, alright :+1:
I'll close this and open an issue with `cmp_luasnip`, since it should be fixed there

**Comment by L3MON4D3** [comment]
(opened https://github.com/saadparwaiz1/cmp_luasnip/issues/58 over there)
